import type { InputMode, ThemeConfig } from './types';

export const THEMES: ThemeConfig[] = [
  {
    key: 'starter',
    label: { en: 'Starter', ar: 'البداية' },
    description: { en: 'Simple & Clean – Perfect for school projects', ar: 'بسيط ونظيف – مثالي للمشاريع المدرسية' },
    bgGradient: 'from-slate-100 to-slate-200',
    cardBg: 'bg-white',
    headerBg: 'bg-slate-700',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accent: 'bg-slate-700',
    bulletColor: 'bg-slate-500',
    imageIntensity: 'none',
    preferredLayouts: ['cover', 'title_and_bullets'],
    cardShadow: 'shadow-lg',
    cardBorder: 'border border-slate-200',
  },
  {
    key: 'professional',
    label: { en: 'Professional', ar: 'احترافي' },
    description: { en: 'Corporate Ready – For business & reports', ar: 'جاهز للأعمال – للتقارير والاجتماعات' },
    bgGradient: 'from-blue-50 to-indigo-100',
    cardBg: 'bg-white',
    headerBg: 'bg-indigo-600',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accent: 'bg-indigo-600',
    bulletColor: 'bg-indigo-500',
    imageIntensity: 'light',
    preferredLayouts: ['cover', 'title_and_bullets', 'two_column'],
    cardShadow: 'shadow-xl',
    cardBorder: 'border border-indigo-100',
  },
  {
    key: 'pitch_deck',
    label: { en: 'Pitch Deck', ar: 'عرض استثماري' },
    description: { en: 'Bold & Visual – For investors & sales', ar: 'جريء ومرئي – للمستثمرين والمبيعات' },
    bgGradient: 'from-emerald-50 to-teal-100',
    cardBg: 'bg-white',
    headerBg: 'bg-emerald-600',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accent: 'bg-emerald-500',
    bulletColor: 'bg-emerald-500',
    imageIntensity: 'heavy',
    preferredLayouts: ['cover', 'image_left_bullets_right', 'three_column_cards', 'title_and_bullets', 'big_stat'],
    cardShadow: 'shadow-2xl',
    cardBorder: 'border-0',
  },
  {
    key: 'creative',
    label: { en: 'Creative', ar: 'إبداعي' },
    description: { en: 'Visual-First – For marketing & events', ar: 'المرئيات أولاً – للتسويق والفعاليات' },
    bgGradient: 'from-orange-400 to-pink-500',
    cardBg: 'bg-white/95',
    headerBg: 'bg-gradient-to-r from-orange-500 to-pink-500',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accent: 'bg-orange-500',
    bulletColor: 'bg-pink-500',
    imageIntensity: 'dominant',
    preferredLayouts: ['cover', 'image_left_bullets_right', 'full_image', 'title_and_bullets'],
    cardShadow: 'shadow-2xl',
    cardBorder: 'border-0',
  },
  {
    key: 'academic',
    label: { en: 'Academic', ar: 'أكاديمي' },
    description: { en: 'Formal & Clear – For lectures & research', ar: 'رسمي وواضح – للمحاضرات والبحث' },
    bgGradient: 'from-slate-800 to-slate-900',
    cardBg: 'bg-slate-800',
    headerBg: 'bg-cyan-500',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    accent: 'bg-cyan-500',
    bulletColor: 'bg-cyan-400',
    imageIntensity: 'light',
    preferredLayouts: ['cover', 'title_and_bullets', 'two_column'],
    cardShadow: 'shadow-2xl',
    cardBorder: 'border border-slate-700',
  },
];

// Input mode options for how Wakti should handle the user's text
export const INPUT_MODES: { key: InputMode; label: { en: string; ar: string }; description: { en: string; ar: string } }[] = [
  {
    key: 'verbatim',
    label: { en: 'Use my text exactly', ar: 'استخدم نصي كما هو' },
    description: { en: 'Turn my words into slides without changing them', ar: 'حوّل كلماتي إلى شرائح دون تغييرها' },
  },
  {
    key: 'polish',
    label: { en: 'Polish & adapt my text', ar: 'حسّن نصي وطوّره' },
    description: { en: 'Improve flow & structure but keep my voice', ar: 'حسّن التدفق والبنية مع الحفاظ على أسلوبي' },
  },
  {
    key: 'topic_only',
    label: { en: 'Treat as topic only', ar: 'استخدمه كموضوع فقط' },
    description: { en: 'Use as inspiration, create fresh content', ar: 'استخدمه كإلهام وأنشئ محتوى جديد' },
  },
  {
    key: 'blank',
    label: { en: 'Blank (start without typing anything)', ar: 'فارغ (ابدأ بدون كتابة شيء)' },
    description: { en: 'Start with empty slides and fill everything in Edit', ar: 'ابدأ بشرائح فارغة واملأ كل شيء في وضع التعديل' },
  },
];

// Dropdown options - expanded with more use cases including personal tributes
export const OBJECTIVES = [
  { key: 'express_love', label: { en: '💕 Express Love / Appreciation', ar: '💕 التعبير عن الحب / التقدير' } },
  { key: 'celebrate_someone', label: { en: '🎉 Celebrate Someone Special', ar: '🎉 الاحتفاء بشخص مميز' } },
  { key: 'school_project', label: { en: '📚 School Project', ar: '📚 مشروع مدرسي' } },
  { key: 'university_thesis', label: { en: '🎓 University Thesis/Research', ar: '🎓 أطروحة جامعية/بحث' } },
  { key: 'pitch_investors', label: { en: '💰 Pitch to Investors', ar: '💰 عرض للمستثمرين' } },
  { key: 'educate_audience', label: { en: '📖 Educate & Inform', ar: '📖 تثقيف وإعلام' } },
  { key: 'sell_product', label: { en: '🛒 Sell Product/Service', ar: '🛒 بيع منتج/خدمة' } },
  { key: 'internal_report', label: { en: '📊 Internal Report', ar: '📊 تقرير داخلي' } },
  { key: 'project_proposal', label: { en: '📝 Project Proposal', ar: '📝 اقتراح مشروع' } },
  { key: 'training', label: { en: '🎯 Training/Workshop', ar: '🎯 تدريب/ورشة عمل' } },
  { key: 'case_study', label: { en: '🔍 Case Study', ar: '🔍 دراسة حالة' } },
  { key: 'company_intro', label: { en: '🏢 Company Introduction', ar: '🏢 تقديم الشركة' } },
];

export const AUDIENCES = [
  { key: 'partner_spouse', label: { en: '💑 My Partner / Spouse', ar: '💑 شريك حياتي / زوجي' } },
  { key: 'family', label: { en: '👨‍👩‍👧‍👦 My Family', ar: '👨‍👩‍👧‍👦 عائلتي' } },
  { key: 'loved_one', label: { en: '❤️ A Loved One', ar: '❤️ شخص عزيز' } },
  { key: 'teachers', label: { en: '👨‍🏫 Teachers/Professors', ar: '👨‍🏫 المعلمون/الأساتذة' } },
  { key: 'classmates', label: { en: '👥 Classmates/Peers', ar: '👥 زملاء الدراسة' } },
  { key: 'students', label: { en: '🎒 Students', ar: '🎒 الطلاب' } },
  { key: 'investors', label: { en: '💼 Investors & VCs', ar: '💼 المستثمرون' } },
  { key: 'executives', label: { en: '👔 Executives & Leadership', ar: '👔 المدراء التنفيذيون' } },
  { key: 'general_public', label: { en: '🌍 General Public', ar: '🌍 الجمهور العام' } },
  { key: 'team_members', label: { en: '🤝 Team Members', ar: '🤝 أعضاء الفريق' } },
  { key: 'clients', label: { en: '🤵 Clients & Customers', ar: '🤵 العملاء' } },
  { key: 'conference', label: { en: '🎤 Conference Attendees', ar: '🎤 حضور المؤتمر' } },
];

export const SCENARIOS = [
  { key: 'anniversary', label: { en: '💍 Anniversary / Special Night', ar: '💍 ذكرى سنوية / ليلة مميزة' } },
  { key: 'private_celebration', label: { en: '🎊 Private Celebration', ar: '🎊 احتفال خاص' } },
  { key: 'wedding_speech', label: { en: '💒 Wedding / Engagement', ar: '💒 زفاف / خطوبة' } },
  { key: 'classroom', label: { en: '🏫 Classroom Presentation', ar: '🏫 عرض في الفصل' } },
  { key: 'school_project', label: { en: '📚 School Project Defense', ar: '📚 دفاع عن مشروع مدرسي' } },
  { key: 'thesis_defense', label: { en: '🎓 Thesis Defense', ar: '🎓 مناقشة الأطروحة' } },
  { key: 'pitch_meeting', label: { en: '💼 Pitch Meeting', ar: '💼 اجتماع عرض' } },
  { key: 'conference', label: { en: '🎤 Conference Talk', ar: '🎤 محاضرة مؤتمر' } },
  { key: 'webinar', label: { en: '💻 Webinar/Online', ar: '💻 ندوة عبر الإنترنت' } },
  { key: 'board_meeting', label: { en: '📋 Board Meeting', ar: '📋 اجتماع مجلس الإدارة' } },
  { key: 'sales_call', label: { en: '📞 Sales Presentation', ar: '📞 عرض مبيعات' } },
  { key: 'workshop', label: { en: '🛠️ Workshop/Training', ar: '🛠️ ورشة عمل/تدريب' } },
];

export const TONES = [
  { key: 'romantic', label: { en: '💕 Romantic', ar: '💕 رومانسي' } },
  { key: 'heartfelt', label: { en: '❤️ Heartfelt & Warm', ar: '❤️ صادق ودافئ' } },
  { key: 'gentle', label: { en: '🌸 Soft & Gentle', ar: '🌸 ناعم ولطيف' } },
  { key: 'playful', label: { en: '😄 Playful & Fun', ar: '😄 مرح وممتع' } },
  { key: 'educational', label: { en: '📖 Educational & Clear', ar: '📖 تعليمي وواضح' } },
  { key: 'professional', label: { en: '💼 Professional', ar: '💼 مهني' } },
  { key: 'casual', label: { en: '😊 Casual & Friendly', ar: '😊 ودي وغير رسمي' } },
  { key: 'inspirational', label: { en: '✨ Inspirational', ar: '✨ ملهم' } },
  { key: 'data_driven', label: { en: '📊 Data-driven', ar: '📊 قائم على البيانات' } },
  { key: 'storytelling', label: { en: '📚 Storytelling', ar: '📚 سرد قصصي' } },
  { key: 'formal', label: { en: '🎩 Formal & Academic', ar: '🎩 رسمي وأكاديمي' } },
  { key: 'persuasive', label: { en: '🎯 Persuasive', ar: '🎯 مقنع' } },
];
