import React, { useState } from 'react';
import { Loader2, Youtube, CheckCircle2, ExternalLink } from 'lucide-react';
import { toast } from 'sonner';
import { useYouTubeConnection } from '@/hooks/useYouTubeConnection';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';

type Props = {
  fileUrl: string;
  title: string;
  description?: string;
  tags?: string[];
  isShort?: boolean;
  language?: string;
};

export default function YouTubePublishBar({
  fileUrl,
  title,
  description = '',
  tags = [],
  isShort = false,
  language = 'en',
}: Props) {
  const isAr = language === 'ar';
  const { connection, connectYouTube, uploadToYouTube } = useYouTubeConnection();
  const [uploadState, setUploadState] = useState<'idle' | 'uploading' | 'done' | 'error'>('idle');
  const [ytUrl, setYtUrl] = useState<string | null>(null);
  const [publishType, setPublishType] = useState<'short' | 'video'>(isShort ? 'short' : 'video');
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [draftTitle, setDraftTitle] = useState(title);
  const [draftDescription, setDraftDescription] = useState('');

  const handlePublish = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!connection.connected) {
      await connectYouTube();
      return;
    }
    if (uploadState === 'done' && ytUrl) {
      window.open(ytUrl, '_blank');
      return;
    }
    if (uploadState === 'uploading') return;
    setIsDialogOpen(true);
  };

  const handleConfirmPublish = async () => {
    if (uploadState === 'uploading') return;

    const cleanTitle = draftTitle.trim();
    if (!cleanTitle) {
      toast.error(isAr ? 'أدخل عنوان الفيديو' : 'Please enter a video title');
      return;
    }

    const watermark = 'Generated by Wakti AI';
    const cleanDescription = draftDescription.trim();
    const finalDescription = cleanDescription
      ? `${cleanDescription}\n\n${watermark}`
      : watermark;

    setUploadState('uploading');
    try {
      const result = await uploadToYouTube({
        fileUrl,
        title: cleanTitle,
        description: finalDescription,
        tags,
        privacy: 'public',
        isShort: publishType === 'short',
      });
      setYtUrl(result.videoUrl);
      setUploadState('done');
      setIsDialogOpen(false);
      toast.success(isAr ? 'تم النشر على يوتيوب!' : 'Published to YouTube!');
    } catch (err: unknown) {
      setUploadState('error');
      const message = err instanceof Error ? err.message : 'Upload failed';
      toast.error(message);
    }
  };

  if (connection.loading) {
    return (
      <div className="flex items-center gap-2 px-3 py-2 rounded-xl border border-white/10 bg-white/[0.04] text-xs text-muted-foreground/50">
        <Loader2 className="h-3 w-3 animate-spin" />
        {isAr ? 'جاري التحقق...' : 'Checking YouTube...'}
      </div>
    );
  }

  if (uploadState === 'done' && ytUrl) {
    return (
      <button
        type="button"
        onClick={() => window.open(ytUrl, '_blank')}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold border border-emerald-400/30 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 active:scale-95 transition-all"
      >
        <CheckCircle2 className="h-3 w-3" />
        {isAr ? 'تم النشر على يوتيوب' : 'Published to YouTube'}
        <ExternalLink className="h-3 w-3 opacity-60" />
      </button>
    );
  }

  if (uploadState === 'uploading') {
    return (
      <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold border border-red-400/20 bg-red-500/10 text-red-400 opacity-70">
        <Loader2 className="h-3 w-3 animate-spin" />
        {isAr ? 'جاري الرفع إلى يوتيوب...' : 'Uploading to YouTube...'}
      </div>
    );
  }

  if (connection.connecting) {
    return (
      <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold border border-red-400/20 bg-red-500/10 text-red-400 opacity-70">
        <Loader2 className="h-3 w-3 animate-spin" />
        {isAr ? 'جاري الفتح...' : 'Opening...'}
      </div>
    );
  }

  return (
    <>
      <div className="flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={handlePublish}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold border border-red-400/30 bg-red-500/10 text-red-400 hover:bg-red-500/20 active:scale-95 transition-all"
        >
          <Youtube className="h-3 w-3" />
          {!connection.connected
            ? (isAr ? 'ربط يوتيوب' : 'Connect YouTube')
            : (isAr ? 'نشر على يوتيوب' : 'Publish to YouTube')}
        </button>
      </div>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent
          className="max-w-md border-white/10 bg-[#0c0f14] text-white"
          title={isAr ? 'النشر على يوتيوب' : 'Publish to YouTube'}
          description={isAr ? 'أدخل بيانات الفيديو قبل النشر' : 'Enter your video details before publishing'}
        >
          <DialogHeader>
            <DialogTitle>{isAr ? 'النشر على يوتيوب' : 'Publish to YouTube'}</DialogTitle>
            <DialogDescription>
              {isAr ? 'أدخل العنوان والوصف ثم اختر شورت أو فيديو.' : 'Enter the title and description, then choose Short or Video.'}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium text-white/90">
                {isAr ? 'العنوان' : 'Title'}
              </label>
              <Input
                value={draftTitle}
                onChange={(e) => setDraftTitle(e.target.value)}
                placeholder={isAr ? 'أدخل عنوان الفيديو' : 'Enter video title'}
                className="border-white/10 bg-white/[0.04] text-white placeholder:text-white/40"
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium text-white/90">
                {isAr ? 'الوصف' : 'Description'}
              </label>
              <Textarea
                value={draftDescription}
                onChange={(e) => setDraftDescription(e.target.value)}
                placeholder={isAr ? 'اكتب وصفًا قصيرًا للفيديو' : 'Write a short description for the video'}
                className="border-white/10 bg-white/[0.04] text-white placeholder:text-white/40"
              />
              <div className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-300">
                {isAr ? 'سيتم إضافة هذا السطر دائمًا: Generated by Wakti AI' : 'This line will always be added: Generated by Wakti AI'}
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium text-white/90">
                {isAr ? 'نوع النشر' : 'Publish type'}
              </label>
              <div className="inline-flex items-center rounded-xl border border-white/10 bg-white/[0.04] p-1">
                <button
                  type="button"
                  onClick={() => setPublishType('short')}
                  className={publishType === 'short'
                    ? 'px-3 py-1.5 rounded-lg text-xs font-semibold bg-red-500/20 text-red-300'
                    : 'px-3 py-1.5 rounded-lg text-xs font-semibold text-muted-foreground hover:text-foreground'}
                >
                  {isAr ? 'شورت' : 'Short'}
                </button>
                <button
                  type="button"
                  onClick={() => setPublishType('video')}
                  className={publishType === 'video'
                    ? 'px-3 py-1.5 rounded-lg text-xs font-semibold bg-blue-500/20 text-blue-300'
                    : 'px-3 py-1.5 rounded-lg text-xs font-semibold text-muted-foreground hover:text-foreground'}
                >
                  {isAr ? 'فيديو' : 'Video'}
                </button>
              </div>
            </div>
          </div>

          <DialogFooter className="gap-2 sm:gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setIsDialogOpen(false)}
              className="border-white/10 bg-white/[0.04] text-white hover:bg-white/[0.08]"
            >
              {isAr ? 'إلغاء' : 'Cancel'}
            </Button>
            <Button
              type="button"
              onClick={handleConfirmPublish}
              disabled={false}
              className="bg-gradient-to-r from-red-500 to-pink-500 text-white hover:opacity-90"
            >
              {publishType === 'short'
                ? (isAr ? 'نشر كشورت' : 'Publish as Short')
                : (isAr ? 'نشر كفيديو' : 'Publish as Video')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
