
import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Download, X, Camera } from 'lucide-react';
import { useTheme } from '@/providers/ThemeProvider';
import { useToastHelper } from "@/hooks/use-toast-helper";
import { useIsMobile } from '@/hooks/use-mobile';

interface ImageModalProps {
  isOpen: boolean;
  onClose: () => void;
  imageUrl: string;
  prompt?: string;
}

export function ImageModal({ isOpen, onClose, imageUrl, prompt }: ImageModalProps) {
  const { language } = useTheme();
  const { showSuccess, showError } = useToastHelper();
  const { isMobile } = useIsMobile();

  const handleSaveToPhotos = async () => {
    try {
      if (isMobile && navigator.share && navigator.canShare) {
        // Mobile: Use Web Share API to save to Photos
        const response = await fetch(imageUrl);
        const blob = await response.blob();
        
        // Create a File object from the blob
        const file = new File([blob], `wakti-ai-generated-${Date.now()}.webp`, {
          type: blob.type,
        });

        // Check if we can share files
        if (navigator.canShare({ files: [file] })) {
          await navigator.share({
            files: [file],
            title: language === 'ar' ? 'صورة من WAKTI AI' : 'WAKTI AI Generated Image',
            text: language === 'ar' ? 'صورة مُولدة بواسطة WAKTI AI' : 'Generated by WAKTI AI',
          });
          
          showSuccess(
            language === 'ar' ? 'تم فتح قائمة المشاركة' : 'Share menu opened - select Photos to save'
          );
          return;
        }
      }
      
      // Fallback: Traditional download for desktop or unsupported devices
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `wakti-ai-generated-${Date.now()}.webp`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      
      showSuccess(
        language === 'ar' ? 'تم حفظ الصورة بنجاح' : 'Image saved successfully'
      );
    } catch (error) {
      console.error('Error saving image:', error);
      showError(
        language === 'ar' ? 'فشل في حفظ الصورة' : 'Failed to save image'
      );
    }
  };

  const getButtonText = () => {
    if (isMobile) {
      return language === 'ar' ? 'حفظ للصور' : 'Save to Photos';
    }
    return language === 'ar' ? 'حفظ الصورة' : 'Save Image';
  };

  const getButtonIcon = () => {
    return isMobile ? <Camera className="h-4 w-4" /> : <Download className="h-4 w-4" />;
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] p-0" hideCloseButton={true}>
        <DialogHeader className="p-4 pb-2">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-lg font-semibold">
              {language === 'ar' ? 'الصورة المُولدة' : 'Generated Image'}
            </DialogTitle>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleSaveToPhotos}
                className="flex items-center gap-2"
              >
                {getButtonIcon()}
                {getButtonText()}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="h-8 w-8 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
          {prompt && (
            <p className="text-sm text-muted-foreground mt-2">
              <strong>{language === 'ar' ? 'الوصف:' : 'Prompt:'}</strong> {prompt}
            </p>
          )}
        </DialogHeader>
        
        <div className="p-4 pt-0">
          <div className="relative bg-muted rounded-lg overflow-hidden">
            <img
              src={imageUrl}
              alt="Generated image"
              className="w-full h-auto max-h-[70vh] object-contain"
            />
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
