import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Download, X, Camera } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useTheme } from '@/providers/ThemeProvider';
import { useToastHelper } from "@/hooks/use-toast-helper";
import { useIsMobile } from '@/hooks/use-mobile';

  interface ImageModalProps {
    isOpen: boolean;
    onClose: () => void;
    imageUrl: string;
    prompt?: string;
  }

export function ImageModal({ isOpen, onClose, imageUrl, prompt }: ImageModalProps) {
  const { language } = useTheme();
  const { showSuccess, showError } = useToastHelper();
  const { isMobile } = useIsMobile();

  const handleSaveToPhotos = async () => {
    try {
      if (isMobile && 'share' in navigator && 'canShare' in navigator) {
        // Mobile (iOS): convert to PNG before sharing to avoid Photos freezing on WebP
        const res = await fetch(imageUrl, { mode: 'cors' });
        const originalBlob = await res.blob();

        const toPng = async (blob: Blob): Promise<Blob | null> => {
          try {
            const bmp = await createImageBitmap(blob);
            const canvas = document.createElement('canvas');
            canvas.width = bmp.width;
            canvas.height = bmp.height;
            const ctx = canvas.getContext('2d');
            if (!ctx) return null;
            ctx.drawImage(bmp, 0, 0);
            return await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
          } catch {
            try {
              const objUrl = URL.createObjectURL(blob);
              const img = await new Promise<HTMLImageElement>((resolve, reject) => {
                const i = new Image();
                i.crossOrigin = 'anonymous';
                i.onload = () => resolve(i);
                i.onerror = reject;
                i.src = objUrl;
              });
              URL.revokeObjectURL(objUrl);
              const canvas = document.createElement('canvas');
              canvas.width = img.naturalWidth || img.width;
              canvas.height = img.naturalHeight || img.height;
              const ctx = canvas.getContext('2d');
              if (!ctx) return null;
              ctx.drawImage(img, 0, 0);
              return await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
            } catch {
              return null;
            }
          }
        };

        const pngBlob = await toPng(originalBlob);
        const shareFile = pngBlob
          ? new File([pngBlob], `wakti-ai-generated-${Date.now()}.png`, { type: 'image/png' })
          : new File([originalBlob], `wakti-ai-generated-${Date.now()}.webp`, { type: originalBlob.type || 'image/webp' });

        if ((navigator as any).canShare({ files: [shareFile] })) {
          await (navigator as any).share({
            files: [shareFile],
            title: language === 'ar' ? 'صورة من WAKTI AI' : 'WAKTI AI Generated Image',
            text: language === 'ar' ? 'صورة مُولدة بواسطة WAKTI AI' : 'Generated by WAKTI AI',
          });
          showSuccess(language === 'ar' ? 'تم فتح قائمة المشاركة' : 'Share menu opened - select Photos to save');
          return;
        }
      }

      // Fallback: Traditional download for desktop or unsupported devices
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `wakti-ai-generated-${Date.now()}.webp`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      showSuccess(language === 'ar' ? 'تم حفظ الصورة بنجاح' : 'Image saved successfully');
    } catch (error) {
      console.error('Error saving image:', error);
      showError(language === 'ar' ? 'فشل في حفظ الصورة' : 'Failed to save image');
    }
  };

  const getButtonText = () => {
    if (isMobile) {
      return language === 'ar' ? 'حفظ للصور' : 'Save to Photos';
    }
    return language === 'ar' ? 'حفظ الصورة' : 'Save Image';
  };

  const getButtonIcon = () => {
    return isMobile ? <Camera className="h-4 w-4" /> : <Download className="h-4 w-4" />;
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] p-0" hideCloseButton={true}>
        <DialogHeader className="p-4 pb-2">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-lg font-semibold">
              {language === 'ar' ? 'الصورة المُولدة' : 'Generated Image'}
            </DialogTitle>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleSaveToPhotos}
                className="flex items-center gap-2"
              >
                {getButtonIcon()}
                {getButtonText()}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="h-8 w-8 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
          {prompt ? (
            <DialogDescription className="mt-2">
              <strong>{language === 'ar' ? 'الوصف:' : 'Prompt:'}</strong> {prompt}
            </DialogDescription>
          ) : (
            <DialogDescription className="sr-only">
              {language === 'ar' ? 'معاينة الصورة المُولدة' : 'Preview of the generated image'}
            </DialogDescription>
          )}
        </DialogHeader>
        
        <div className="p-4 pt-0">
          <div className="relative bg-muted rounded-lg overflow-hidden">
            <img
              src={imageUrl}
              alt="Generated image"
              className="w-full h-auto max-h-[70vh] object-contain"
            />
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
