import {
  A4_THEMES,
  findTheme,
  getThemeDocumentLane,
  getThemeFormSchema,
  maxPagesForTheme,
  themeRequiresPurpose,
  type A4DocumentLane,
  type A4FormField,
  type A4Theme,
} from "../../../../supabase/functions/_shared/a4-themes.ts";

export {
  A4_THEMES,
  findTheme,
  getThemeDocumentLane,
  maxPagesForTheme,
  themeRequiresPurpose,
  type A4DocumentLane,
  type A4FormField,
  type A4Theme,
};

export function getFormSchema(theme: A4Theme, purposeId: string | null): A4FormField[] {
  return getThemeFormSchema(theme, purposeId);
}

const BASIC_FIELD_KEYS_BY_THEME: Record<string, string[]> = {
  official_exam: [
    "institution_name",
    "education_level",
    "subject",
    "teacher_name",
    "grade",
    "term",
    "duration",
    "total_marks",
    "instructions",
    "logo",
    "bilingual",
    "raw_content",
  ],
  school_project: [
    "institution_name",
    "education_level",
    "student_name",
    "student_id",
    "grade",
    "department_or_faculty",
    "subject",
    "teacher_or_supervisor",
    "submission_date",
    "project_title",
    "logo",
    "bilingual",
    "raw_content",
  ],
  academic_report: [
    "institution_name",
    "department_or_faculty",
    "course_name",
    "student_name",
    "student_id",
    "instructor_name",
    "supervisor_name",
    "year_or_semester",
    "submission_date",
    "title",
    "logo",
    "bilingual",
    "raw_content",
  ],
  study_handout: [
    "topic",
    "course_name",
    "teacher_name",
    "grade",
    "education_level",
    "focus_area",
    "session_title",
    "exam_scope",
    "formula_focus",
    "logo",
    "bilingual",
    "raw_content",
  ],
  research_poster: [
    "poster_title",
    "institution_name",
    "department_or_faculty",
    "authors",
    "supervisor_name",
    "conference_name",
    "event_name",
    "logo",
    "bilingual",
    "raw_content",
  ],
  corporate_brief: [
    "company_name",
    "department",
    "client_name",
    "report_title",
    "period",
    "author",
    "doc_ref",
    "logo",
    "bilingual",
    "raw_content",
  ],
  certificate: [
    "issuer_name",
    "recipient_name",
    "achievement",
    "issue_date",
    "signatory_name",
    "signatory_title",
    "certificate_title",
    "program_name",
    "category_or_reason",
    "logo",
    "bilingual",
  ],
  event_flyer: [
    "event_name",
    "date",
    "time",
    "venue",
    "tagline",
    "description",
    "cta",
    "headline_image",
    "logo",
    "bilingual",
  ],
  craft_infographic: [
    "topic",
    "institution_name",
    "student_name",
    "grade",
    "subject",
    "teacher_or_supervisor",
    "company_name",
    "department",
    "audience",
    "logo",
    "bilingual",
    "raw_content",
  ],
  comic_explainer: [
    "title",
    "panel_count",
    "raw_content",
    "logo",
  ],
  clean_minimal: [
    "title",
    "subtitle",
    "author",
    "date",
    "sender_name",
    "recipient_name",
    "subject",
    "issuer",
    "event_name",
    "venue",
    "cta",
    "logo",
    "bilingual",
    "raw_content",
  ],
  invoice_receipt: [
    "company_name",
    "client_name",
    "invoice_number",
    "receipt_number",
    "issue_date",
    "due_date",
    "paid_method",
    "currency",
    "payment_terms",
    "logo",
    "bilingual",
    "raw_content",
  ],
  menu_price_list: [
    "business_name",
    "subtitle",
    "currency",
    "contact_info",
    "working_hours",
    "logo",
    "bilingual",
    "raw_content",
  ],
  thank_you_invitation_card: [
    "sender_name",
    "recipient_name",
    "card_title",
    "date",
    "host_name",
    "event_name",
    "event_date",
    "time",
    "venue",
    "dress_code",
    "rsvp",
    "logo",
    "bilingual",
    "raw_content",
  ],
  resume_cv: [
    "full_name",
    "desired_role",
    "email",
    "phone",
    "location",
    "website",
    "linkedin",
    "instagram",
    "whatsapp",
    "summary",
    "education",
    "experience",
    "skills",
    "languages",
    "certifications",
    "awards",
    "hobbies",
    "logo",
    "bilingual",
    "raw_content",
  ],
};

export function isBasicFieldForTheme(themeId: string, fieldKey: string): boolean {
  const keys = BASIC_FIELD_KEYS_BY_THEME[themeId];
  if (!keys) return true;
  return keys.includes(fieldKey);
}

export function searchThemes(query: string): A4Theme[] {
  const q = query.trim().toLowerCase();
  if (!q) return A4_THEMES;
  return A4_THEMES.filter((theme) => {
    if (theme.name_en.toLowerCase().includes(q) || theme.name_ar.includes(q)) return true;
    return (theme.search_aliases ?? []).some((alias) => alias.toLowerCase().includes(q));
  });
}
