import React, { useState, useEffect, useRef, useCallback } from "react";
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameMonth, 
  isSameDay, addMonths, subMonths, startOfWeek, endOfWeek, getDay, 
  addWeeks, subWeeks, setMonth, getMonth, startOfYear, endOfYear, 
  setYear, getYear, addYears, subYears, parse, addHours } from "date-fns";
import { toast } from "sonner";
import { arSA, enUS } from "date-fns/locale";
import { useTheme } from "@/providers/ThemeProvider";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { JournalService, JournalCheckin, JournalDay } from "@/services/journalService";
import { t } from "@/utils/translations";
import { CalendarControls } from "./CalendarControls";
import { CalendarGrid } from "./CalendarGrid";
import { CalendarAgenda } from "./CalendarAgenda";
import { CalendarEntryDialog } from "./CalendarEntryDialog";
import { CalendarViewSwitcher } from "./CalendarViewSwitcher";
import { CalendarEntry, CalendarView, EntryType } from "@/utils/calendarUtils";
import { useOptimizedCalendarData } from "@/hooks/useOptimizedCalendarData";
import { 
  Drawer, 
  DrawerContent, 
  DrawerTrigger, 
  DrawerClose
} from "@/components/ui/drawer";
import { 
  Calendar as CalendarIcon,
  ChevronLeft, 
  ChevronRight, 
  Plus,
  ChevronDown,
  CheckSquare,
  Bell,
  PinIcon,
  Heart,
  Smartphone,
  RefreshCw,
  ExternalLink,
  Copy,
  Check
} from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { Switch } from "@/components/ui/switch";
import {
  isNativeCalendarAvailable,
  createCalendarEvent,
  retrieveCalendars,
  getUserTimezone,
  createCalendarIfSupported
} from "@/integrations/natively/calendarBridge";
import { AppleLogo } from "./AppleLogo";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

export const UnifiedCalendar: React.FC = React.memo(() => {
  const { language, theme } = useTheme();
  const { user } = useAuth();
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState<Date | null>(new Date());
  const [view, setView] = useState<CalendarView>('month');
  const [agendaOpen, setAgendaOpen] = useState(false);
  const [entryDialogOpen, setEntryDialogOpen] = useState(false);
  const [editEntry, setEditEntry] = useState<CalendarEntry | null>(null);
  const [journalDialogOpen, setJournalDialogOpen] = useState(false);
  const [journalLatest, setJournalLatest] = useState<JournalCheckin | null>(null);
  const [journalDay, setJournalDay] = useState<JournalDay | null>(null);
  const [gestureStartY, setGestureStartY] = useState<number | null>(null);
  const [pinchStartDistance, setPinchStartDistance] = useState<number | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const doubleTapTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const lastTapRef = useRef<number>(0);
  
  // Calendar subscription state
  const [calendarFeedToken, setCalendarFeedToken] = useState<string | null>(null);
  const [showSubscribeDialog, setShowSubscribeDialog] = useState(false);
  const [urlCopied, setUrlCopied] = useState(false);
  
  // Phone calendar sync state (legacy - keeping for now)
  const [autoSyncEnabled, setAutoSyncEnabled] = useState<boolean>(() => {
    try {
      return localStorage.getItem('wakti_calendar_auto_sync') === 'true';
    } catch {
      return false;
    }
  });
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncDirection, setSyncDirection] = useState<'both' | 'to_phone' | 'from_phone'>(() => {
    try {
      const saved = localStorage.getItem('wakti_calendar_sync_direction');
      if (saved === 'both' || saved === 'to_phone' || saved === 'from_phone') {
        return saved;
      }
      return 'both';
    } catch {
      return 'both';
    }
  });
  const [nativeCalendarAvailable, setNativeCalendarAvailable] = useState(false);
  
  // Check if native calendar is available on mount
  useEffect(() => {
    setNativeCalendarAvailable(isNativeCalendarAvailable());
  }, []);
  
  // Fetch calendar feed token (token is generated by database migration)
  useEffect(() => {
    const fetchToken = async () => {
      if (!user?.id) return;
      
      try {
        const { data: profile, error } = await supabase
          .from('profiles')
          .select('calendar_feed_token')
          .eq('id', user.id)
          .single() as { data: { calendar_feed_token: string | null } | null; error: any };
        
        if (error) {
          console.error('Error fetching calendar token:', error);
          return;
        }
        
        if (profile?.calendar_feed_token) {
          console.log('Calendar token fetched successfully');
          setCalendarFeedToken(profile.calendar_feed_token);
        } else {
          console.error('No calendar token found in database');
        }
      } catch (err) {
        console.error('Error with calendar token:', err);
      }
    };
    
    fetchToken();
  }, [user?.id]);
  
  // Generate the calendar subscription URL
  const getCalendarSubscribeUrl = useCallback(() => {
    if (!user?.id || !calendarFeedToken) return null;
    const baseUrl = 'https://hxauxozopvpzpdygoqwf.supabase.co/functions/v1/calendar-ics-feed';
    return `${baseUrl}?user_id=${user.id}&token=${encodeURIComponent(calendarFeedToken)}`;
  }, [user?.id, calendarFeedToken]);
  
  // Get webcal URL (for direct subscription)
  const getWebcalUrl = useCallback(() => {
    const httpUrl = getCalendarSubscribeUrl();
    if (!httpUrl) return null;
    return httpUrl.replace('https://', 'webcal://');
  }, [getCalendarSubscribeUrl]);
  
  // Handle subscribe to calendar
  const handleSubscribeToCalendar = useCallback(() => {
    console.log('Subscribe button clicked');
    console.log('User ID:', user?.id);
    console.log('Calendar Feed Token:', calendarFeedToken);
    
    const webcalUrl = getWebcalUrl();
    console.log('Webcal URL:', webcalUrl);
    
    if (!webcalUrl) {
      toast.error(language === 'ar' ? 'جاري تحميل الرابط...' : 'Loading subscription URL...');
      return;
    }
    
    // Use window.open for better iOS compatibility
    const opened = window.open(webcalUrl, '_self');
    if (!opened) {
      // Fallback: try location.href
      window.location.href = webcalUrl;
    }
  }, [getWebcalUrl, user?.id, calendarFeedToken, language]);
  
  // Copy URL to clipboard
  const handleCopyUrl = useCallback(async () => {
    const url = getCalendarSubscribeUrl();
    if (url) {
      try {
        await navigator.clipboard.writeText(url);
        setUrlCopied(true);
        toast.success(language === 'ar' ? 'تم نسخ الرابط' : 'URL copied!');
        setTimeout(() => setUrlCopied(false), 2000);
      } catch {
        toast.error(language === 'ar' ? 'فشل النسخ' : 'Failed to copy');
      }
    }
  }, [getCalendarSubscribeUrl, language]);
  
  // Use optimized calendar data hook to prevent freezing!
  const {
    entries: calendarEntries,
    manualEntries,
    maw3dEvents,
    tasks,
    reminders,
    refresh: refreshCalendarData,
    setManualEntries,
    loading,
  } = useOptimizedCalendarData();
  
  // Get the appropriate locale based on the selected language
  const locale = language === 'ar' ? arSA : enUS;

  // Generate month options for the select
  const months = Array.from({ length: 12 }, (_, i) => {
    const date = new Date();
    date.setMonth(i);
    return {
      value: i.toString(),
      label: format(date, 'MMMM', { locale }),
    };
  });

  // Generate year options (past 2 years, current year, future 5 years)
  const currentYear = new Date().getFullYear();
  const years = Array.from({ length: 8 }, (_, i) => {
    const year = currentYear - 2 + i;
    return {
      value: year.toString(),
      label: year.toString(),
    };
  });

  // Handle navigation between dates
  const navigatePrevious = useCallback(() => {
    if (view === 'month') {
      setCurrentDate(subMonths(currentDate, 1));
    } else if (view === 'week') {
      setCurrentDate(subWeeks(currentDate, 1));
    } else if (view === 'year') {
      setCurrentDate(subYears(currentDate, 1));
    }
  }, [view, currentDate]);

  const navigateNext = useCallback(() => {
    if (view === 'month') {
      setCurrentDate(addMonths(currentDate, 1));
    } else if (view === 'week') {
      setCurrentDate(addWeeks(currentDate, 1));
    } else if (view === 'year') {
      setCurrentDate(addYears(currentDate, 1));
    }
  }, [view, currentDate]);

  const goToToday = useCallback(() => {
    setCurrentDate(new Date());
    setSelectedDate(new Date());
  }, []);

  // Handle month change from dropdown
  const handleMonthChange = useCallback((value: string) => {
    const newMonth = parseInt(value, 10);
    const newDate = setMonth(currentDate, newMonth);
    setCurrentDate(newDate);
  }, [currentDate]);

  // Handle year change from dropdown
  const handleYearChange = useCallback((value: string) => {
    const newYear = parseInt(value, 10);
    const newDate = setYear(currentDate, newYear);
    setCurrentDate(newDate);
  }, [currentDate]);

  // touch gesture handlers
  const handleTouchStart = (e: React.TouchEvent) => {
    if (e.touches.length === 1) {
      // Single touch - track for double tap
      const now = Date.now();
      const timeSinceLastTap = now - lastTapRef.current;
      
      if (timeSinceLastTap < 300) {
        // Double tap detected - switch view
        cycleView();
        
        // Clear any existing timeout to prevent multiple actions
        if (doubleTapTimeoutRef.current) {
          clearTimeout(doubleTapTimeoutRef.current);
          doubleTapTimeoutRef.current = null;
        }
      } else {
        // Set up potential double tap
        lastTapRef.current = now;
      }
      
      setGestureStartY(e.touches[0].clientY);
    } else if (e.touches.length === 2) {
      // Pinch gesture - calculate distance for pinch-to-zoom
      const distance = Math.hypot(
        e.touches[0].clientX - e.touches[1].clientX,
        e.touches[0].clientY - e.touches[1].clientY
      );
      setPinchStartDistance(distance);
    }
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    if (e.touches.length === 2 && pinchStartDistance !== null) {
      const currentDistance = Math.hypot(
        e.touches[0].clientX - e.touches[1].clientX,
        e.touches[0].clientY - e.touches[1].clientY
      );
      
      // If pinching out (zoom in)
      if (currentDistance - pinchStartDistance > 50) {
        if (view === 'year') {
          setView('month');
        } else if (view === 'month') {
          setView('week');
        }
        setPinchStartDistance(null);
      }
      // If pinching in (zoom out)
      else if (pinchStartDistance - currentDistance > 50) {
        if (view === 'week') {
          setView('month');
        } else if (view === 'month') {
          setView('year');
        }
        setPinchStartDistance(null);
      }
    }
  };

  const handleTouchEnd = () => {
    setGestureStartY(null);
    setPinchStartDistance(null);
  };

  // Handle day selection
  const handleDayClick = useCallback((date: Date) => {
    setSelectedDate(date);
    setCurrentDate(date);
    setJournalDialogOpen(false);
    setAgendaOpen(true);
  }, []);

  // Fetch journal data when the journal dialog opens
  useEffect(() => {
    const run = async () => {
      if (!journalDialogOpen || !selectedDate) return;
      const dayStr = format(selectedDate, 'yyyy-MM-dd');
      try {
        const [day, checks] = await Promise.all([
          JournalService.getDay(dayStr),
          JournalService.getCheckinsForDay(dayStr)
        ]);
        setJournalDay(day);
        setJournalLatest((checks && checks.length > 0) ? checks[0] : null);
      } catch {
        setJournalDay(null);
        setJournalLatest(null);
      }
    };
    run();
  }, [journalDialogOpen, selectedDate]);

  // Render note lines as pills (same as TimelineTab)
  const renderNotePills = (text?: string | null) => {
    if (!text) return null;
    const lines = (text || '').split('\n');
    return (
      <div className="mt-2">
        {lines.map((rawLine, idx) => {
          const i = rawLine.indexOf('|');
          if (i < 0) return <div key={`note-line-${idx}`} className="text-sm">{rawLine}</div>;
          const before = rawLine.slice(0, i);
          const after = rawLine.slice(i);
          const parts = after.split('|').map(s => s.trim());
          const markerRe = /^__FREE__(.*)__END__$/;
          let noteFreeText = '';
          const tokensRaw: string[] = [];
          for (const p of parts) {
            if (!p) continue;
            const m = p.match(markerRe);
            if (m) { noteFreeText = m[1]; continue; }
            if (p === '🕒' || p === '__UNSAVED__') continue;
            tokensRaw.push(p);
          }
          const tokens = Array.from(new Set(tokensRaw));
          return (
            <div key={`pill-${idx}`} className="my-2 p-3 rounded-2xl border border-slate-200 bg-gradient-to-br from-white to-slate-50 text-slate-800 shadow-sm">
              <span className="text-xs text-slate-600 mr-1">{before.match(/\[[^\]]+\]/)?.[0] || before}</span>
              <span className="sr-only"> | </span>
              <span className="inline-flex flex-wrap gap-2 align-middle">
                {tokens.map((tok, k) => (
                  <span key={`tok-${k}`} className="inline-flex items-center gap-1 rounded-full border border-slate-300 bg-white text-slate-800 px-2 py-0.5 shadow text-xs">{tok}</span>
                ))}
                {noteFreeText && (
                  <span className="inline-flex items-center gap-1 rounded-full border border-slate-300 bg-white text-slate-800 px-2 py-0.5 shadow text-xs">{noteFreeText}</span>
                )}
              </span>
            </div>
          );
        })}
      </div>
    );
  };

  // Add a new manual calendar entry - optimized to prevent freezing
  const addManualEntry = useCallback((entry: Omit<CalendarEntry, 'id'>) => {
    const newEntry: CalendarEntry = {
      ...entry,
      id: `manual-${Date.now()}`,
      type: EntryType.MANUAL_NOTE,
    };
    console.log('Adding new manual entry:', newEntry);
    const updatedEntries = [...manualEntries, newEntry];
    setManualEntries(updatedEntries);
    setEntryDialogOpen(false);
  }, [manualEntries, setManualEntries]);

  // Edit a manual calendar entry - optimized
  const updateManualEntry = useCallback((entry: CalendarEntry) => {
    console.log('Updating manual entry:', entry);
    const updatedEntries = manualEntries.map(e => e.id === entry.id ? entry : e);
    setManualEntries(updatedEntries);
    setEditEntry(null);
    setEntryDialogOpen(false);
  }, [manualEntries, setManualEntries]);

  // Delete a manual calendar entry - optimized
  const deleteManualEntry = useCallback((entryId: string) => {
    console.log('Deleting manual entry with ID:', entryId);
    const updatedEntries = manualEntries.filter(entry => entry.id !== entryId);
    setManualEntries(updatedEntries);
    setEditEntry(null);
    setEntryDialogOpen(false);
  }, [manualEntries, setManualEntries]);

  // Open dialog to edit an entry
  const handleEditEntry = useCallback((entry: CalendarEntry) => {
    if (entry.type === EntryType.MANUAL_NOTE) {
      setEditEntry(entry);
      setEntryDialogOpen(true);
    }
  }, []);

  const cycleView = useCallback(() => {
    setView(prev => {
      if (prev === 'month') return 'week';
      if (prev === 'week') return 'year';
      return 'month';
    });
  }, []);

  // Sync calendar entries to phone calendar
  const syncToPhoneCalendar = useCallback(async () => {
    console.log('[CalendarSync] syncToPhoneCalendar called');
    
    setIsSyncing(true);
    const timezone = getUserTimezone();
    let successCount = 0;
    let failCount = 0;
    
    // Get synced events from localStorage for deduplication
    const recentlySyncedEvents: Record<string, number> = (() => {
      try {
        const stored = localStorage.getItem('wakti_synced_events');
        return stored ? JSON.parse(stored) : {};
      } catch {
        return {};
      }
    })();
    
    // Current timestamp for tracking synced events
    const now = Date.now();
    
    // Clear old entries (older than 24 hours)
    const ONE_DAY = 24 * 60 * 60 * 1000; // 24 hours in milliseconds
    const freshSyncedEvents: Record<string, number> = {};
    for (const [key, timestamp] of Object.entries(recentlySyncedEvents)) {
      if (now - timestamp < ONE_DAY) {
        freshSyncedEvents[key] = timestamp;
      }
    }
    
    // Sync ALL calendar entry types: Tasks, Reminders, Maw3d, Manual, Journal, Events, Appointments, Project Bookings
    // Filter to only include entries with valid date strings AND not recently synced
    const entriesToSync = calendarEntries.filter(e => 
      // Filter by entry type - include ALL types except PHONE_CALENDAR (those come FROM phone, not TO phone)
      (e.type === EntryType.TASK || 
       e.type === EntryType.REMINDER || 
       e.type === EntryType.MAW3D_EVENT ||
       e.type === EntryType.PROJECT_BOOKING ||
       e.type === EntryType.EVENT ||
       e.type === EntryType.APPOINTMENT ||
       e.type === EntryType.MANUAL_NOTE ||
       e.type === EntryType.JOURNAL) &&
      // Validate date is present and valid
      e.date && 
      typeof e.date === 'string' &&
      e.date.length >= 10 && // At least 'yyyy-MM-dd'
      // Deduplication - don't sync if recently synced
      !freshSyncedEvents[`${e.id}-${e.title}-${e.date}`]
    );
    
    console.log('[CalendarSync] Entries to sync:', entriesToSync.length, entriesToSync.map(e => ({ title: e.title, type: e.type, date: e.date })));
    
    if (entriesToSync.length === 0) {
      setIsSyncing(false);
      toast.info(
        language === 'ar' 
          ? 'لا توجد أحداث جديدة للمزامنة. جميع الأحداث تمت مزامنتها بالفعل.' 
          : 'No new events to sync. All events are already synced.'
      );
      return;
    }
    
    // First, retrieve available calendars from the device
    const calendarResult = await new Promise<{ calendarId: string | null; error: string | null }>((resolve) => {
      retrieveCalendars((result) => {
        console.log('[CalendarSync] Retrieved calendars result:', result);
        if (result.status === 'SUCCESS' && result.data && result.data.length > 0) {
          const waktiCalendar = result.data.find((calendar) => (calendar.name || '').toLowerCase().includes('wakti'));
          if (waktiCalendar) {
            resolve({ calendarId: waktiCalendar.id, error: null });
            return;
          }

          createCalendarIfSupported('Wakti', (createResult) => {
            if (createResult.status === 'SUCCESS' && createResult.id) {
              resolve({ calendarId: createResult.id, error: null });
            } else {
              resolve({
                calendarId: result.data?.[0]?.id || null,
                error: createResult.error || 'Unable to create Wakti calendar'
              });
            }
          });
        } else if (result.status === 'SUCCESS') {
          createCalendarIfSupported('Wakti', (createResult) => {
            if (createResult.status === 'SUCCESS' && createResult.id) {
              resolve({ calendarId: createResult.id, error: null });
            } else {
              resolve({ calendarId: null, error: createResult.error || 'Unable to create Wakti calendar' });
            }
          });
        } else {
          console.warn('[CalendarSync] Failed to retrieve calendars:', result.error);
          resolve({ calendarId: null, error: result.error || 'No calendars available' });
        }
      });
    });

    const calendarId = calendarResult.calendarId;
    console.log('[CalendarSync] Using calendar ID:', calendarId, '| Error:', calendarResult.error);
    
    // If calendar retrieval failed, show error
    if (calendarId === null) {
      setIsSyncing(false);
      const errorDetail = calendarResult.error || '';
      toast.error(
        language === 'ar' 
          ? `لا يمكن الوصول إلى التقويم: ${errorDetail}. يرجى السماح بالوصول في الإعدادات → الخصوصية → التقويمات → Wakti` 
          : `Cannot access calendar: ${errorDetail}. Please allow access in Settings → Privacy → Calendars → Wakti`
      );
      return;
    }
    
    let lastError = '';
    
    for (const entry of entriesToSync) {
      try {
        // Skip entries without a valid date string
        if (!entry.date || typeof entry.date !== 'string') {
          console.error('[CalendarSync] Entry missing date:', entry.title);
          failCount++;
          continue;
        }
        
        // Parse date safely - handle both 'yyyy-MM-dd' and ISO formats
        let entryDate: Date;
        const datePart = entry.date.split('T')[0];
        const dateParts = datePart.split('-');
        
        if (dateParts.length !== 3) {
          console.error('[CalendarSync] Invalid date format for entry:', entry.title, entry.date);
          failCount++;
          continue;
        }
        
        const [year, month, day] = dateParts.map(Number);
        
        // Validate parsed numbers
        if (isNaN(year) || isNaN(month) || isNaN(day)) {
          console.error('[CalendarSync] Could not parse date numbers for entry:', entry.title, entry.date);
          failCount++;
          continue;
        }
        
        entryDate = new Date(year, month - 1, day, 9, 0, 0); // Default to 9 AM if no time
        
        if (entry.time && typeof entry.time === 'string') {
          const timeParts = entry.time.split(':');
          if (timeParts.length >= 2) {
            const [hours, minutes] = timeParts.map(Number);
            entryDate.setHours(isNaN(hours) ? 9 : hours, isNaN(minutes) ? 0 : minutes, 0, 0);
          }
        }
        
        // Validate date object is valid
        if (isNaN(entryDate.getTime())) {
          console.error('[CalendarSync] Invalid date for entry:', entry.title, entry.date);
          failCount++;
          continue;
        }
        
        // Clone the date to avoid mutation issues
        const startDateObj = new Date(entryDate.getTime());
        const endDateObj = addHours(new Date(entryDate.getTime()), 1);
        
        // Safe logging - don't call toISOString if date is invalid
        const safeISOString = (d: Date) => {
          try {
            return d instanceof Date && !isNaN(d.getTime()) ? d.toISOString() : 'INVALID_DATE';
          } catch {
            return 'ERROR';
          }
        };
        
        console.log('[CalendarSync] Creating event:', { 
          title: entry.title, 
          startDate: safeISOString(startDateObj), 
          endDate: safeISOString(endDateObj), 
          timezone, 
          calendarId, 
          rawDate: entry.date 
        });
        
        await new Promise<void>((resolve) => {
          createCalendarEvent(
            entry.title,
            startDateObj,
            endDateObj,
            timezone,
            calendarId,
            entry.description || null,
            (result) => {
              console.log('[CalendarSync] Create event result:', result);
              if (result.status === 'SUCCESS') {
                successCount++;
                // Record successful sync in deduplication tracking
                const syncKey = `${entry.id}-${entry.title}-${entry.date}`;
                freshSyncedEvents[syncKey] = now;
              } else {
                failCount++;
                lastError = result.error || 'Unknown error';
                console.warn('[CalendarSync] Failed to sync entry:', entry.title, result.error);
              }
              resolve();
            }
          );
        });
      } catch (err) {
        failCount++;
        console.error('[CalendarSync] Error syncing entry:', entry.title, err);
      }
    }
    
    // Save the updated synced events to localStorage for deduplication
    try {
      localStorage.setItem('wakti_synced_events', JSON.stringify(freshSyncedEvents));
      console.log('[CalendarSync] Saved synced events tracking:', Object.keys(freshSyncedEvents).length);
    } catch (err) {
      console.error('[CalendarSync] Error saving synced events:', err);
    }
    
    setIsSyncing(false);
    
    if (successCount > 0) {
      toast.success(
        language === 'ar' 
          ? `تمت مزامنة ${successCount} حدث إلى تقويم الهاتف` 
          : `Synced ${successCount} events to phone calendar`
      );
    }
    if (failCount > 0) {
      toast.error(
        language === 'ar' 
          ? `فشل في مزامنة ${failCount} حدث: ${lastError}` 
          : `Failed to sync ${failCount} events: ${lastError}`
      );
    }
  }, [calendarEntries, language]);

  // Helper function to sync events using direct NativelyCalendar SDK
  const syncEventsToCalendar = (calendar: any, calendarId: string) => {
    console.log('[DirectSDK] Starting event sync to calendar ID:', calendarId);
    
    // Filter entries to sync - ALL entry types except PHONE_CALENDAR (those come FROM phone)
    const entriesToSync = calendarEntries.filter(e => 
      e.date && 
      typeof e.date === 'string' && 
      e.date.length >= 10 &&
      e.type !== EntryType.PHONE_CALENDAR // Don't sync phone events back to phone
    );
    
    // Log breakdown by type for debugging
    const typeBreakdown = entriesToSync.reduce((acc, e) => {
      acc[e.type] = (acc[e.type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    
    console.log('[DirectSDK] Found', entriesToSync.length, 'events to sync');
    console.log('[DirectSDK] Type breakdown:', typeBreakdown);
    
    if (entriesToSync.length === 0) {
      toast.info(
        language === 'ar' 
          ? 'لا توجد أحداث للمزامنة' 
          : 'No events to sync'
      );
      setIsSyncing(false);
      return;
    }
    
    let successCount = 0;
    let failCount = 0;
    let totalToProcess = entriesToSync.length;
    
    // Get timezone
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
    console.log('[DirectSDK] Using timezone:', timezone);
    
    // Process each event
    entriesToSync.forEach((entry, index) => {
      try {
        // Parse date safely
        const datePart = entry.date.split('T')[0];
        const dateParts = datePart.split('-');
        
        if (dateParts.length !== 3) {
          console.error('[DirectSDK] Invalid date format for entry:', entry.title, entry.date);
          failCount++;
          return;
        }
        
        const [year, month, day] = dateParts.map(Number);
        
        // Validate parsed numbers
        if (isNaN(year) || isNaN(month) || isNaN(day)) {
          console.error('[DirectSDK] Could not parse date numbers for entry:', entry.title, entry.date);
          failCount++;
          return;
        }
        
        // Set start and end dates
        let startDateObj = new Date(year, month - 1, day, 9, 0, 0); // Default to 9 AM
        
        // Use time if available
        if (entry.time && typeof entry.time === 'string') {
          const timeParts = entry.time.split(':');
          if (timeParts.length >= 2) {
            const [hours, minutes] = timeParts.map(Number);
            startDateObj.setHours(isNaN(hours) ? 9 : hours, isNaN(minutes) ? 0 : minutes, 0, 0);
          }
        }
        
        // Create end date 1 hour after start
        let endDateObj = new Date(startDateObj.getTime());
        endDateObj.setHours(endDateObj.getHours() + 1);
        
        // Format to ISO string for NativelyCalendar
        const startDate = startDateObj.toISOString();
        const endDate = endDateObj.toISOString();
        
        console.log('[DirectSDK] Creating event:', { 
          title: entry.title, 
          startDate, 
          endDate, 
          calendarId,
          description: entry.description || ''
        });
        
        // Create event using direct SDK
        calendar.createCalendarEvent(
          entry.title,
          endDate,
          startDate,
          timezone,
          calendarId,
          entry.description || '',
          function(result: any) {
            console.log('[DirectSDK] Create event result:', result);
            
            if (result.status === 'SUCCESS') {
              successCount++;
              console.log(`[DirectSDK] Event created: ${entry.title}`);
            } else {
              failCount++;
              console.error(`[DirectSDK] Failed to create event: ${entry.title}`, result.error);
            }
            
            // Check if all events are processed
            if (successCount + failCount === totalToProcess) {
              // All done
              setIsSyncing(false);
              
              if (successCount > 0) {
                toast.success(
                  language === 'ar'
                    ? `تمت مزامنة ${successCount} من الأحداث بنجاح${failCount > 0 ? ` (فشل ${failCount})` : ''}`
                    : `Successfully synced ${successCount} events${failCount > 0 ? ` (${failCount} failed)` : ''}`
                );
              } else {
                toast.error(
                  language === 'ar'
                    ? 'فشلت مزامنة الأحداث'
                    : 'Failed to sync events'
                );
              }
            }
          }
        );
      } catch (err) {
        console.error('[DirectSDK] Error creating event:', err);
        failCount++;
        
        // Check if all events are processed
        if (successCount + failCount === totalToProcess) {
          setIsSyncing(false);
          toast.error(
            language === 'ar'
              ? 'حدث خطأ أثناء مزامنة التقويم'
              : 'Error occurred during calendar sync'
          );
        }
      }
    });
  };

  // Bidirectional calendar sync - handle both directions
  const syncCalendars = useCallback(async (direction: 'both' | 'to_phone' | 'from_phone' = 'both') => {
    console.log('[CalendarSync] Starting sync with direction:', direction);
    console.log('[CalendarSync] nativeCalendarAvailable:', nativeCalendarAvailable);
    
    if (isSyncing) {
      console.log('[CalendarSync] Sync already in progress, skipping...');
      return;
    }
    
    setIsSyncing(true);
    let syncSuccess = false;
    let toPhoneSuccess = false;
    let fromPhoneSuccess = false;
    let errorMessage = '';
    
    try {
      // Send to phone (Wakti → Phone)
      if (direction === 'both' || direction === 'to_phone') {
        console.log('[CalendarSync] Syncing TO phone...');
        try {
          await syncToPhoneCalendar();
          toPhoneSuccess = true;
          console.log('[CalendarSync] Sync TO phone completed');
        } catch (toPhoneError) {
          console.error('[CalendarSync] Error syncing TO phone:', toPhoneError);
          errorMessage = String(toPhoneError);
        }
      }
      
      // Fetch from phone (Phone → Wakti)
      if (direction === 'both' || direction === 'from_phone') {
        console.log('[CalendarSync] Syncing FROM phone...');
        try {
          await refreshCalendarData(); // This includes retrieveCalendarEventsIfSupported
          fromPhoneSuccess = true;
          console.log('[CalendarSync] Sync FROM phone completed');
        } catch (fromPhoneError) {
          console.error('[CalendarSync] Error syncing FROM phone:', fromPhoneError);
          if (!errorMessage) errorMessage = String(fromPhoneError);
        }
      }
      
      // Determine overall success
      if (direction === 'both') {
        syncSuccess = toPhoneSuccess || fromPhoneSuccess; // At least one direction worked
      } else if (direction === 'to_phone') {
        syncSuccess = toPhoneSuccess;
      } else {
        syncSuccess = fromPhoneSuccess;
      }
    } catch (error) {
      console.error('[CalendarSync] Sync error:', error);
      errorMessage = String(error);
    } finally {
      setIsSyncing(false);
    }
    
    if (syncSuccess) {
      const msg = {
        both: language === 'ar' ? 'تمت مزامنة التقويم بنجاح' : 'Calendar synced successfully',
        to_phone: language === 'ar' ? 'تمت مزامنة التقويم إلى الهاتف' : 'Calendar synced to phone',
        from_phone: language === 'ar' ? 'تمت مزامنة التقويم من الهاتف' : 'Calendar synced from phone'
      };
      toast.success(msg[direction]);
    } else {
      // Show specific error message
      const isInApp = typeof (window as any).natively !== 'undefined' || 
                      typeof (window as any).NativelyCalendar !== 'undefined' ||
                      (window as any).natively?.isNativeApp === true;
      if (!isInApp) {
        // Not in native app - show info and open ICS subscription dialog as fallback
        toast.info(
          language === 'ar' 
            ? 'افتح التطبيق على هاتفك للمزامنة المباشرة، أو استخدم الاشتراك' 
            : 'Open the app on your phone for direct sync, or use subscription'
        );
        setShowSubscribeDialog(true);
        return;
      } else {
        toast.error(
          language === 'ar'
            ? 'فشلت المزامنة. تأكد من منح صلاحيات التقويم'
            : 'Sync failed. Please grant calendar permissions'
        );
      }
      console.error('[CalendarSync] Sync failed:', errorMessage);
    }
  }, [language, isSyncing, syncToPhoneCalendar, refreshCalendarData]);

  // Handle auto-sync toggle
  const handleAutoSyncToggle = useCallback((enabled: boolean) => {
    setAutoSyncEnabled(enabled);
    try {
      localStorage.setItem('wakti_calendar_auto_sync', enabled ? 'true' : 'false');
    } catch {}
    
    if (enabled) {
      toast.success(
        language === 'ar' 
          ? 'تم تفعيل المزامنة التلقائية' 
          : 'Auto-sync enabled'
      );
      // Trigger immediate sync when enabled
      syncCalendars(syncDirection);
    } else {
      toast.info(
        language === 'ar' 
          ? 'تم إيقاف المزامنة التلقائية' 
          : 'Auto-sync disabled'
      );
    }
  }, [language, syncCalendars, syncDirection]);
  
  // Handle sync direction change
  const handleSyncDirectionChange = useCallback((direction: 'both' | 'to_phone' | 'from_phone') => {
    setSyncDirection(direction);
    try {
      localStorage.setItem('wakti_calendar_sync_direction', direction);
    } catch {}
    
    const directionLabels = {
      both: language === 'ar' ? 'ثنائي الإتجاه' : 'Bidirectional',
      to_phone: language === 'ar' ? 'إلى الهاتف فقط' : 'To Phone Only',
      from_phone: language === 'ar' ? 'من الهاتف فقط' : 'From Phone Only'
    };
    
    toast.info(
      language === 'ar'
        ? `تم تغيير اتجاه المزامنة إلى: ${directionLabels[direction]}` 
        : `Sync direction changed to: ${directionLabels[direction]}`
    );
  }, [language]);

  const handleSyncClick = useCallback(async () => {
    const availableNow = isNativeCalendarAvailable();
    setNativeCalendarAvailable(availableNow);

    if (!availableNow) {
      toast.error(
        language === 'ar'
          ? 'مزامنة التقويم غير متاحة. تأكد من منح صلاحيات التقويم في إعدادات التطبيق.'
          : 'Calendar sync is not available. Please ensure calendar permissions are granted in the app settings.'
      );
      return;
    }

    toast.info(language === 'ar' ? 'جاري المزامنة...' : 'Syncing...');

    let timeoutId: ReturnType<typeof setTimeout> | null = null;
    timeoutId = setTimeout(() => {
      if (isSyncing) {
        toast.error(
          language === 'ar'
            ? 'انتهت مهلة المزامنة. حاول مرة أخرى وتأكد من صلاحيات التقويم.'
            : 'Sync timed out. Please try again and confirm calendar permissions.'
        );
        setIsSyncing(false);
      }
    }, 15000);

    try {
      await syncCalendars(syncDirection);
      refreshCalendarData();
    } finally {
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
    }
  }, [language, refreshCalendarData, syncCalendars, syncDirection, isSyncing]);


  // Auto-sync when calendar data changes (if enabled)
  useEffect(() => {
    let autoSyncTimeout: NodeJS.Timeout;
    
    const triggerAutoSync = () => {
      if (autoSyncEnabled && nativeCalendarAvailable && calendarEntries.length > 0 && !isSyncing) {
        console.log('[CalendarSync] Auto-sync scheduled');
        // Debounce auto-sync to prevent multiple rapid syncs
        clearTimeout(autoSyncTimeout);
        autoSyncTimeout = setTimeout(() => {
          console.log('[CalendarSync] Auto-sync executing...');
          syncCalendars(syncDirection);
        }, 2000); // Wait 2 seconds after last change
      }
    };
    
    triggerAutoSync();
    
    return () => {
      clearTimeout(autoSyncTimeout);
    };
  }, [autoSyncEnabled, nativeCalendarAvailable, calendarEntries.length, syncDirection, syncCalendars, isSyncing]);

  return (
    <div 
      className="flex flex-col h-full w-full overflow-hidden" 
      ref={containerRef}
    >
      <div className="flex flex-col space-y-2 p-3">
        {/* Top bar with sync and date controls */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between w-full gap-2">
          {/* Sync controls - button and auto-sync toggle */}
          <div className="flex items-center gap-2 relative z-50">
            <button
              type="button"
              disabled={isSyncing}
              onClick={() => {
                console.log('[SyncButton] CLICKED!');
                alert('Sync button clicked!');
                handleSyncClick();
              }}
              className="px-4 py-2 rounded-md text-sm font-medium bg-primary text-primary-foreground disabled:opacity-50 cursor-pointer touch-manipulation"
            >
              {language === 'ar' ? 'مزامنة' : 'Sync'}
            </button>
            
            {/* Auto-sync toggle */}
            <div className="flex items-center gap-1.5">
              <Switch
                checked={autoSyncEnabled}
                onCheckedChange={handleAutoSyncToggle}
                disabled={!nativeCalendarAvailable || isSyncing}
                className="scale-75"
              />
              <span className="text-xs text-muted-foreground whitespace-nowrap">
                {language === 'ar' ? 'تلقائي' : 'Auto'}
              </span>
            </div>
          </div>
          
          {/* Date controls */}
          <div className="flex items-center flex-wrap gap-2">
            <Button 
              variant="ghost" 
              size="icon"
              onClick={navigatePrevious}
              className={cn(language === 'ar' ? 'order-2' : 'order-1')}
            >
              <ChevronLeft className={cn("h-5 w-5", language === 'ar' && "rotate-180")} />
            </Button>
            
            <div className={cn("flex items-center gap-1", 
              language === 'ar' ? 'order-1 flex-row-reverse' : 'order-2')}>
              <Select 
                value={getMonth(currentDate).toString()}
                onValueChange={handleMonthChange}
              >
                <SelectTrigger className="w-[110px] sm:w-[130px]">
                  <SelectValue>
                    {format(currentDate, 'MMMM', { locale })}
                  </SelectValue>
                </SelectTrigger>
                <SelectContent>
                  {months.map(month => (
                    <SelectItem key={month.value} value={month.value}>
                      {month.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              
              <Select 
                value={getYear(currentDate).toString()}
                onValueChange={handleYearChange}
              >
                <SelectTrigger className="w-[84px] sm:w-[90px]">
                  <SelectValue>
                    {format(currentDate, 'yyyy', { locale })}
                  </SelectValue>
                </SelectTrigger>
                <SelectContent>
                  {years.map(year => (
                    <SelectItem key={year.value} value={year.value}>
                      {year.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <Button 
              variant="ghost" 
              size="icon"
              onClick={navigateNext}
              className={cn(language === 'ar' ? 'order-1' : 'order-3')}
            >
              <ChevronRight className={cn("h-5 w-5", language === 'ar' && "rotate-180")} />
            </Button>
          </div>
        </div>

        {/* Updated Legend with proper color coding */}
        <div className="flex items-center justify-center">
          <div className="flex items-center gap-3 text-xs text-muted-foreground flex-wrap justify-center">
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-purple-500"></div>
              <span>{language === 'ar' ? 'مواعيد' : 'Maw3d'}</span>
            </div>
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-yellow-500"></div>
              <span>{language === 'ar' ? 'يدوي' : 'Manual'}</span>
            </div>
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-green-500"></div>
              <span>{language === 'ar' ? 'مهام' : 'Tasks'}</span>
            </div>
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-red-500"></div>
              <span>{language === 'ar' ? 'تذكيرات' : 'Reminders'}</span>
            </div>
            <div className="flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-sky-500"></div>
              <span>{language === 'ar' ? 'دفتر' : 'Journal'}</span>
            </div>
            <div className="flex items-center gap-1">
              <AppleLogo size={12} className="text-black dark:text-white" />
              <span>{language === 'ar' ? 'الهاتف' : 'Phone'}</span>
            </div>
          </div>
        </div>
        
        {/* View switcher and action buttons */}
        <div className="flex items-center justify-between">
          <CalendarViewSwitcher 
            view={view} 
            onViewChange={setView}
          />
          
          <div className="flex items-center space-x-2">
            <Button 
              variant="outline" 
              size="sm" 
              onClick={goToToday}
            >
              {t("today", language)}
            </Button>

            {/* Floating Add Button */}
            <Button 
              variant="outline" 
              size="icon" 
              onClick={() => {
                setEditEntry(null);
                setEntryDialogOpen(true);
              }}
              title={t("create", language)}
              className="fixed bottom-24 right-4 z-10 rounded-full shadow-lg h-12 w-12 bg-primary text-primary-foreground hover:bg-primary/90"
            >
              <Plus className="h-6 w-6" />
            </Button>
            
          </div>
        </div>
        
      </div>

      <div
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        <CalendarGrid
          currentDate={currentDate}
          selectedDate={selectedDate}
          calendarEntries={calendarEntries}
          view={view}
          onDayClick={handleDayClick}
          language={language}
          locale={locale}
        />
      </div>

      

      <Drawer open={agendaOpen} onOpenChange={setAgendaOpen}>
        <DrawerTrigger asChild>
          <div />
        </DrawerTrigger>
        <DrawerContent className="max-h-[85vh]">
          <div className="p-4">
            {selectedDate && (
              <CalendarAgenda 
                date={selectedDate}
                entries={calendarEntries}
                onClose={() => setAgendaOpen(false)}
                onEditEntry={handleEditEntry}
              />
            )}
          </div>
        </DrawerContent>
      </Drawer>

      <CalendarEntryDialog
        isOpen={entryDialogOpen}
        onClose={() => {
          setEntryDialogOpen(false);
          setEditEntry(null);
        }}
        onSave={editEntry ? updateManualEntry : addManualEntry}
        onDelete={editEntry ? deleteManualEntry : undefined}
        initialDate={selectedDate || new Date()}
        entry={editEntry}
      />

      {/* Subscribe to Calendar Dialog - iOS Optimized */}
      <Dialog open={showSubscribeDialog} onOpenChange={setShowSubscribeDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-center text-xl">
              {language === 'ar' ? '📅 مزامنة التقويم' : '📅 Sync Your Calendar'}
            </DialogTitle>
          </DialogHeader>
          
          <div className="space-y-5 py-4">
            {/* iOS-style explanation */}
            <div className="text-center space-y-2">
              <p className="text-sm text-muted-foreground">
                {language === 'ar' 
                  ? 'اضغط الزر أدناه وسيفتح تطبيق التقويم تلقائياً'
                  : 'Tap the button below and your Calendar app will open automatically'}
              </p>
              <p className="text-xs text-muted-foreground">
                {language === 'ar' 
                  ? 'ثم اضغط "اشتراك" للمزامنة التلقائية'
                  : 'Then tap "Subscribe" for automatic sync'}
              </p>
            </div>
            
            {/* Simple URL Display */}
            <div className="bg-muted/50 rounded-lg p-4 space-y-3">
              <p className="text-sm font-medium">
                {language === 'ar' ? 'رابط التقويم:' : 'Calendar URL:'}
              </p>
              <div className="flex items-center gap-2">
                <input
                  id="calendar-url-input"
                  type="text"
                  readOnly
                  value={getWebcalUrl() || ''}
                  title={language === 'ar' ? 'رابط التقويم' : 'Calendar URL'}
                  aria-label={language === 'ar' ? 'رابط التقويم' : 'Calendar URL'}
                  className="flex-1 px-3 py-2 text-sm bg-white dark:bg-gray-800 rounded-md border truncate"
                  onFocus={(e) => e.target.select()}
                />
                <button
                  type="button"
                  onClick={() => {
                    const url = getWebcalUrl();
                    if (url) {
                      // Try multiple copy methods
                      if (navigator.clipboard && navigator.clipboard.writeText) {
                        navigator.clipboard.writeText(url).then(() => {
                          setUrlCopied(true);
                          toast.success(language === 'ar' ? 'تم نسخ الرابط!' : 'URL copied!');
                          setTimeout(() => setUrlCopied(false), 2000);
                        }).catch(() => {
                          // Fallback: select and copy
                          const input = document.getElementById('calendar-url-input') as HTMLInputElement;
                          if (input) {
                            input.select();
                            document.execCommand('copy');
                            setUrlCopied(true);
                            toast.success(language === 'ar' ? 'تم نسخ الرابط!' : 'URL copied!');
                            setTimeout(() => setUrlCopied(false), 2000);
                          }
                        });
                      } else {
                        // Fallback for older browsers
                        const input = document.getElementById('calendar-url-input') as HTMLInputElement;
                        if (input) {
                          input.select();
                          document.execCommand('copy');
                          setUrlCopied(true);
                          toast.success(language === 'ar' ? 'تم نسخ الرابط!' : 'URL copied!');
                          setTimeout(() => setUrlCopied(false), 2000);
                        }
                      }
                    }
                  }}
                  style={{
                    padding: '8px 12px',
                    backgroundColor: urlCopied ? '#22c55e' : '#f3f4f6',
                    color: urlCopied ? '#fff' : '#374151',
                    border: '1px solid #d1d5db',
                    borderRadius: '6px',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  {urlCopied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                </button>
              </div>
              <p className="text-xs text-muted-foreground">
                {language === 'ar' ? 'اضغط على الرابط لتحديده، ثم انسخه' : 'Tap the URL to select it, then copy'}
              </p>
            </div>
            
            {/* Instructions */}
            <div className="bg-blue-50 dark:bg-blue-950/30 rounded-xl p-4 space-y-3">
              <p className="text-sm font-medium">
                {language === 'ar' ? 'كيفية الاشتراك:' : 'How to subscribe:'}
              </p>
              <ol className="text-sm text-muted-foreground space-y-2 list-decimal list-inside">
                <li>1. {language === 'ar' ? 'انسخ الرابط أعلاه' : 'Copy the URL above'}</li>
                <li>2. {language === 'ar' ? 'افتح تطبيق التقويم' : 'Open your Calendar app'}</li>
                <li>3. {language === 'ar' ? 'اضغط على الإعدادات ثم إضافة اشتراك' : 'Go to Settings then Add Subscription'}</li>
                <li>4. {language === 'ar' ? 'الصق الرابط واضغط اشتراك' : 'Paste the URL and tap Subscribe'}</li>
              </ol>
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-500 text-white flex items-center justify-center text-xs font-bold">2</div>
                <p className="text-sm text-muted-foreground">
                  {language === 'ar' ? 'اضغط "اشتراك" في النافذة المنبثقة' : 'Tap "Subscribe" in the popup'}
                </p>
              </div>
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-6 h-6 rounded-full bg-green-500 text-white flex items-center justify-center text-xs font-bold">✓</div>
                <p className="text-sm text-muted-foreground">
                  {language === 'ar' ? 'تمت المزامنة! ستظهر أحداثك تلقائياً' : 'Done! Your events will sync automatically'}
                </p>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
});

UnifiedCalendar.displayName = 'UnifiedCalendar';

export default UnifiedCalendar;
