import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { isNativelyApp } from '@/integrations/natively/browserBridge';
import { ArrowLeft } from 'lucide-react';

const APP_STORE_URL = 'https://apps.apple.com/us/app/wakti-ai/id6755150700';
const LOGO_URL = '/lovable-uploads/cffe5d1a-e69b-4cd9-ae4c-43b58d4bfbb4.png';

interface ImageRecord {
  id: string;
  image_url: string;
  prompt: string | null;
  submode: string | null;
  created_at: string;
}

export default function ImageShare() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [image, setImage] = useState<ImageRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const isInApp = isNativelyApp();

  useEffect(() => {
    const load = async () => {
      if (!id) {
        setError('Invalid link');
        setLoading(false);
        return;
      }

      try {
        const { data, error: fetchErr } = await (supabase as any)
          .from('user_generated_images')
          .select('id, image_url, prompt, submode, created_at')
          .eq('id', id)
          .maybeSingle();

        if (fetchErr || !data) {
          setError('Image not found');
          setLoading(false);
          return;
        }

        setImage(data);
      } catch {
        setError('Something went wrong');
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [id]);

  // Update page title and OG meta for social sharing
  useEffect(() => {
    if (image) {
      document.title = 'Image by Wakti AI';
      // Set OG meta tags dynamically for link previews
      const setMeta = (property: string, content: string) => {
        let el = document.querySelector(`meta[property="${property}"]`) as HTMLMetaElement;
        if (!el) {
          el = document.createElement('meta');
          el.setAttribute('property', property);
          document.head.appendChild(el);
        }
        el.setAttribute('content', content);
      };
      setMeta('og:title', 'Image by Wakti AI');
      setMeta('og:description', image.prompt || 'Created with Wakti AI');
      setMeta('og:image', image.image_url);
      setMeta('og:type', 'website');
    }
  }, [image]);

  // ─── Loading ───
  if (loading) {
    return (
      <div className="min-h-screen bg-[#0c0f14] flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-white/20 border-t-white rounded-full animate-spin" />
      </div>
    );
  }

  // ─── Error ───
  if (error || !image) {
    return (
      <div className="min-h-screen bg-[#0c0f14] flex flex-col items-center justify-center gap-4 px-6">
        <img src={LOGO_URL} alt="Wakti" className="w-16 h-16 rounded-2xl" />
        <p className="text-white/70 text-lg">{error || 'Image not found'}</p>
        <a
          href={APP_STORE_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="mt-4 px-6 py-3 rounded-2xl bg-gradient-to-r from-[#060541] to-purple-600 text-white font-semibold text-sm flex items-center gap-2 active:scale-95 transition-transform"
        >
          Download Wakti AI
        </a>
      </div>
    );
  }

  // ─── Branded Share Page ───
  return (
    <div className="min-h-screen bg-[#0c0f14] flex flex-col">
      {/* Header */}
      <header className="flex items-center justify-between px-5 py-4">
        <div className="flex items-center gap-3">
          {isInApp && (
            <button
              onClick={() => navigate('/dashboard')}
              className="flex items-center gap-1 px-3 py-2 rounded-xl bg-white/10 border border-white/10 text-white text-sm font-semibold active:scale-95 transition-transform"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Wakti
            </button>
          )}
          <img src={LOGO_URL} alt="Wakti" className="w-10 h-10 rounded-xl shadow-lg" />
          <div>
            <h1 className="text-white font-bold text-base leading-tight">Wakti AI</h1>
            <p className="text-white/40 text-[11px]">Creative Studio</p>
          </div>
        </div>
      </header>

      {/* Image */}
      <div className="flex-1 flex items-center justify-center px-4 py-4">
        <div className="relative max-w-2xl w-full">
          <img
            src={image.image_url}
            alt={image.prompt || 'Generated image'}
            className="w-full rounded-2xl shadow-[0_8px_40px_hsla(0,0%,0%,0.6)] border border-white/[0.06]"
          />
        </div>
      </div>

      {/* Footer */}
      <footer className="px-5 pb-8 pt-2 space-y-4">
        {/* Generated by badge */}
        <div className="flex items-center justify-center gap-2">
          <img src={LOGO_URL} alt="" className="w-5 h-5 rounded-md" />
          <p className="text-white/50 text-[11px] font-medium tracking-wide uppercase">
            Generated by Wakti AI
          </p>
        </div>

        {/* CTA: Back to Wakti (in-app) or Download Wakti AI (browser) */}
        {isInApp ? (
          <button
            onClick={() => navigate('/dashboard')}
            className="w-full max-w-sm mx-auto flex items-center justify-center gap-2 py-3.5 rounded-2xl bg-gradient-to-r from-[#060541] via-purple-600 to-blue-600 text-white font-bold text-sm shadow-[0_4px_24px_hsla(260,70%,50%,0.4)] active:scale-[0.97] transition-transform"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Wakti
          </button>
        ) : (
          <a
            href={APP_STORE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="w-full max-w-sm mx-auto flex items-center justify-center gap-2 py-3.5 rounded-2xl bg-gradient-to-r from-[#060541] via-purple-600 to-blue-600 text-white font-bold text-sm shadow-[0_4px_24px_hsla(260,70%,50%,0.4)] active:scale-[0.97] transition-transform"
          >
            <img src={LOGO_URL} alt="" className="w-5 h-5 rounded-md" />
            Download Wakti AI
          </a>
        )}
      </footer>
    </div>
  );
}
