import React, { useMemo } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Download, ExternalLink } from 'lucide-react';

const APP_STORE_URL = 'https://apps.apple.com/us/app/wakti-ai/id6755150700';
const WAKTI_LOGO = '/lovable-uploads/4ed7b33a-201e-4f05-94de-bac892155c01.png';

export default function QRTextView() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();

  // Decode text from URL param (base64url encoded)
  const text = useMemo(() => {
    const t = searchParams.get('t');
    if (!t) return '';
    try {
      let base64 = t.replace(/-/g, '+').replace(/_/g, '/');
      while (base64.length % 4) base64 += '=';
      return decodeURIComponent(escape(atob(base64)));
    } catch {
      return t;
    }
  }, [searchParams]);

  // Check if user likely has the app (came from in-app browser)
  const isInApp = useMemo(() => {
    const ua = navigator.userAgent.toLowerCase();
    return ua.includes('natively') || ua.includes('wakti');
  }, []);

  if (!text) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0c0f14] text-white p-6">
        <div className="text-center space-y-4">
          <img src={WAKTI_LOGO} alt="Wakti" className="w-16 h-16 mx-auto rounded-2xl" />
          <p className="text-lg font-semibold">No content found</p>
          <p className="text-sm text-gray-400">This QR code link appears to be empty or invalid.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#0c0f14] via-[#0f1219] to-[#0c0f14] text-white">
      {/* Header */}
      <header className="sticky top-0 z-10 backdrop-blur-xl bg-[#0c0f14]/80 border-b border-white/[0.06]">
        <div className="max-w-2xl mx-auto px-4 py-3 flex items-center gap-3">
          <button
            onClick={() => {
              if (window.history.length > 1) {
                navigate(-1);
              } else {
                navigate('/dashboard');
              }
            }}
            className="p-2 -ml-2 rounded-xl hover:bg-white/[0.06] active:scale-95 transition-all"
            aria-label="Go back"
          >
            <ArrowLeft className="h-5 w-5 text-gray-300" />
          </button>
          <div className="flex items-center gap-2.5 flex-1 min-w-0">
            <img src={WAKTI_LOGO} alt="Wakti" className="w-8 h-8 rounded-lg flex-shrink-0" />
            <span className="text-sm font-semibold text-gray-300 truncate">Wakti QR</span>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-4 py-8 space-y-8">
        {/* Text Card */}
        <div className="rounded-3xl bg-gradient-to-br from-white/[0.06] to-white/[0.02] border border-white/[0.08] shadow-[0_8px_40px_hsla(0,0%,0%,0.4)] overflow-hidden">
          <div className="px-6 py-4 border-b border-white/[0.06]">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-gradient-to-r from-sky-400 to-indigo-500" />
              <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Shared Message</span>
            </div>
          </div>
          <div className="px-6 py-6">
            <p className="text-base md:text-lg leading-relaxed text-gray-100 whitespace-pre-wrap break-words">
              {text}
            </p>
          </div>
        </div>

        {/* Generated by Wakti + Download CTA (for non-app users) */}
        {!isInApp && (
          <div className="rounded-3xl bg-gradient-to-br from-[#060541]/40 via-purple-900/20 to-[#060541]/40 border border-purple-500/10 p-6 space-y-5">
            <div className="flex items-center gap-4">
              <img
                src={WAKTI_LOGO}
                alt="Wakti AI"
                className="w-14 h-14 rounded-2xl shadow-[0_4px_20px_hsla(260,70%,50%,0.3)]"
              />
              <div>
                <h3 className="text-lg font-bold text-white">Wakti AI</h3>
                <p className="text-sm text-gray-400">Your intelligent digital partner</p>
              </div>
            </div>

            <p className="text-sm text-gray-300 leading-relaxed">
              This message was shared via <span className="font-semibold text-white">Wakti</span> — the ultimate productivity AI app. Create QR codes, manage tasks, chat with AI, and much more.
            </p>

            <a
              href={APP_STORE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2.5 w-full px-6 py-3.5 rounded-2xl bg-gradient-to-r from-[#060541] to-purple-700 text-white font-bold text-sm shadow-[0_8px_32px_hsla(260,70%,40%,0.4)] hover:shadow-[0_8px_40px_hsla(260,70%,40%,0.5)] active:scale-[0.98] transition-all"
            >
              <Download className="h-5 w-5" />
              Download Wakti AI
              <ExternalLink className="h-3.5 w-3.5 opacity-60" />
            </a>

            <p className="text-[11px] text-gray-500 text-center">
              Available on iOS & Android
            </p>
          </div>
        )}

        {/* Footer branding */}
        <div className="text-center pb-8">
          <p className="text-xs text-gray-600">
            Generated with Wakti QR Code Creator
          </p>
        </div>
      </main>
    </div>
  );
}
