import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface TranscriptPdfOptions {
  content: string;
  videoUrl?: string | null;
  language: string;
  // 'transcript' = video transcript sheet · 'answer' = any chat answer shared as PDF
  kind?: 'transcript' | 'answer';
}

// Escape user/model text before placing it into the HTML shell
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Turn the transcript text into styled HTML: [MM:SS - MM:SS] lines become section
// headers, everything else becomes paragraphs. RTL-safe for Arabic transcripts.
function transcriptBodyToHtml(content: string, isArabic: boolean): string {
  const lines = (content || '').split('\n');
  const out: string[] = [];
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) {
      out.push('<div style="height:8px"></div>');
      continue;
    }
    const escaped = escapeHtml(line);
    if (/^\[\d{1,2}:\d{2}(\s*-\s*\d{1,2}:\d{2})?\]/.test(line)) {
      out.push(
        `<div style="margin-top:18px;padding:6px 12px;background:linear-gradient(135deg,#060541 0%,#2a2670 100%);color:#f2f2f2;border-radius:8px;font-weight:700;font-size:13px;direction:${isArabic ? 'rtl' : 'ltr'};">${escaped}</div>`
      );
    } else {
      out.push(`<p style="margin:6px 0;font-size:13px;line-height:1.7;color:#1f2430;">${escaped}</p>`);
    }
  }
  return out.join('');
}

/**
 * Branded Wakti PDF export for video transcripts.
 * Renders a styled HTML sheet off-screen (html2canvas handles Arabic/RTL perfectly),
 * then slices it into A4 pages with jsPDF.
 */
export async function downloadTranscriptPdf({ content, videoUrl, language, kind = 'transcript' }: TranscriptPdfOptions): Promise<void> {
  const isArabic = language === 'ar';
  const isTranscript = kind === 'transcript';
  const subtitle = isTranscript
    ? (isArabic ? 'تفريغ فيديو' : 'Video Transcript')
    : (isArabic ? 'إجابة من وقتي' : 'Wakti Answer');
  const filePrefix = isTranscript ? 'wakti-transcript' : 'wakti-answer';
  const today = new Date().toLocaleDateString(isArabic ? 'ar-QA' : 'en-GB', { year: 'numeric', month: 'long', day: 'numeric' });

  const shell = document.createElement('div');
  shell.style.cssText = 'position:fixed;left:-10000px;top:0;width:794px;background:#fcfefd;font-family:system-ui,-apple-system,"Segoe UI","Noto Sans Arabic",Tahoma,sans-serif;';
  shell.innerHTML = `
    <div style="border:1px solid #e5e2d8;border-radius:16px;overflow:hidden;">
      <div style="background:linear-gradient(135deg,#060541 0%,#2a2670 60%,#060541 100%);padding:24px 32px;display:flex;align-items:center;justify-content:space-between;direction:ltr;">
        <div>
          <div style="color:#f2f2f2;font-size:22px;font-weight:800;letter-spacing:0.5px;">WAKTI AI</div>
          <div style="color:#e9ceb0;font-size:12px;margin-top:2px;">${subtitle}</div>
        </div>
        <div style="color:#858384;font-size:11px;text-align:right;">
          <div>${today}</div>
          <div style="margin-top:2px;">wakti.qa</div>
        </div>
      </div>
      ${videoUrl ? `<div style="padding:12px 32px;background:#f5f3ec;border-bottom:1px solid #e5e2d8;font-size:11px;color:#606062;direction:ltr;word-break:break-all;">${escapeHtml(videoUrl)}</div>` : ''}
      <div style="padding:24px 32px;direction:${isArabic ? 'rtl' : 'ltr'};text-align:${isArabic ? 'right' : 'left'};">
        ${transcriptBodyToHtml(content, isArabic)}
      </div>
      <div style="padding:14px 32px;border-top:1px solid #e5e2d8;font-size:10px;color:#858384;text-align:center;">
        ${isArabic ? 'تم الإنشاء بواسطة WAKTI AI — wakti.qa' : 'Generated by WAKTI AI — wakti.qa'}
      </div>
    </div>
  `;
  document.body.appendChild(shell);

  try {
    const canvas = await html2canvas(shell, { scale: 2, backgroundColor: '#fcfefd', useCORS: true });
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 10;
    const imgWidth = pageWidth - margin * 2;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = margin;
    const imgData = canvas.toDataURL('image/png');

    pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - margin * 2;
    while (heightLeft > 0) {
      pdf.addPage();
      position = heightLeft - imgHeight + margin;
      pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
      heightLeft -= pageHeight - margin * 2;
    }

    pdf.save(`${filePrefix}-${new Date().toISOString().slice(0, 10)}.pdf`);
  } finally {
    document.body.removeChild(shell);
  }
}
