// deno-lint-ignore-file no-explicit-any
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { buildTrialErrorPayload, buildTrialSuccessPayload, checkAndConsumeTrialTokenOnce, checkTrialAccess } from "../_shared/trial-tracker.ts";
import { logAIFromRequest } from "../_shared/aiLogger.ts";
import { inspectGenerationPrompt } from "../_shared/promptSafety.ts";

// Grok Imagine Image 2.0 — Segment Map (free) + Image Edit (paid, counts as t2i).
// Both take a task_id of an image previously generated by grok-imagine-image-2-0.
// Flow: submit → returns taskId → frontend polls this same function with { taskId, action }.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const KIE_API_KEY = (
  Deno.env.get("KIE_AI_API_KEY")
  || Deno.env.get("KIE_API_KEY")
  || Deno.env.get("NANO_BANANA_API_KEY")
  || Deno.env.get("KIE_BEARER_TOKEN")
  || ""
).trim();

const MODEL_SEGMENT = "grok-imagine-image-2-0/segment-map";
const MODEL_EDIT = "grok-imagine-image-2-0/image-edit";
// jobs/createTask is Kie's proven unified door (their /client/tasks docs endpoint 404'd at launch).
// If the unified door ever rejects these models, we retry once on the documented endpoint.
const KIE_CREATE_TASK_ENDPOINT = "https://api.kie.ai/api/v1/jobs/createTask";
const KIE_CLIENT_TASKS_ENDPOINT = "https://api.kie.ai/api/v1/client/tasks";
const KIE_RECORD_INFO_ENDPOINT = "https://api.kie.ai/api/v1/jobs/recordInfo";
const MAX_SEGMENTS = 40;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}

// Recursively find an array of segment objects ({ name, index, maskUrl-ish }) anywhere in the payload
function findSegments(root: any): any[] {
  let best: any[] = [];
  const visit = (node: any, depth: number) => {
    if (!node || depth > 8) return;
    if (Array.isArray(node)) {
      const looksLikeSegments = node.length > 0 && node.every((item) =>
        item && typeof item === "object"
        && (typeof item.name === "string" || typeof item.label === "string")
        && (typeof item.index === "number" || typeof item.index === "string" || typeof item.idx === "number")
      );
      if (looksLikeSegments && node.length > best.length) best = node;
      for (const item of node) visit(item, depth + 1);
      return;
    }
    if (typeof node === "object") {
      for (const v of Object.values(node)) visit(v, depth + 1);
    }
  };
  visit(root, 0);
  return best;
}

function normalizeSegment(raw: any): { name: string; index: number; maskUrl: string } | null {
  const name = String(raw?.name ?? raw?.label ?? "").trim();
  const index = Number(raw?.index ?? raw?.idx);
  const maskUrl = String(raw?.maskUrl ?? raw?.mask_url ?? raw?.mask ?? "").trim();
  if (!name || !Number.isFinite(index)) return null;
  return { name, index, maskUrl: maskUrl.startsWith("http") ? maskUrl : "" };
}

// Download a mask image and return it as a base64 data URL (avoids browser CORS issues).
async function fetchMaskAsDataUrl(url: string): Promise<string> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 8000);
  try {
    const resp = await fetch(url, { signal: controller.signal });
    if (!resp.ok) return "";
    const buf = new Uint8Array(await resp.arrayBuffer());
    if (buf.length === 0 || buf.length > 2_000_000) return "";
    let binary = "";
    const CHUNK = 0x8000;
    for (let i = 0; i < buf.length; i += CHUNK) {
      binary += String.fromCharCode(...buf.subarray(i, i + CHUNK));
    }
    const mime = resp.headers.get("content-type")?.split(";")[0] || "image/png";
    return `data:${mime};base64,${btoa(binary)}`;
  } catch {
    return "";
  } finally {
    clearTimeout(timer);
  }
}

function extractImageUrls(data: any): string[] {
  const urls: string[] = [];
  if (typeof data?.resultJson === "string" && data.resultJson) {
    try {
      const parsed = JSON.parse(data.resultJson);
      if (Array.isArray(parsed?.resultUrls)) {
        for (const u of parsed.resultUrls) {
          if (typeof u === "string" && u.startsWith("http")) urls.push(u);
        }
      }
    } catch { /* ignore */ }
  }
  if (urls.length > 0) return urls;
  const seen = new Set<string>();
  const scan = (obj: any, depth = 0) => {
    if (!obj || typeof obj !== "object" || depth > 8) return;
    for (const [k, v] of Object.entries(obj)) {
      if (typeof v === "string" && v.startsWith("http") && !seen.has(v)) {
        const keyLooksImagey = /url|image|img|src|uri|link|photo|pic/i.test(k);
        const hasImageExt = /\.(png|jpg|jpeg|webp)/i.test(v);
        if (keyLooksImagey || hasImageExt) { seen.add(v); urls.push(v); }
      } else if (v && typeof v === "object") scan(v, depth + 1);
    }
  };
  scan(data);
  return urls;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const startTime = Date.now();
  let logModel = MODEL_EDIT;

  try {
    const body = await req.json().catch(() => ({}));
    const action: string = body?.action === "segment" ? "segment" : "edit";
    const userId: string = body?.user_id || "";
    const language = body?.language === "ar" ? "ar" : "en";
    const pollTaskId: string = (body?.taskId || "").toString().trim();
    logModel = action === "segment" ? MODEL_SEGMENT : MODEL_EDIT;

    if (!KIE_API_KEY) {
      return json({ success: false, error: "KIE_API_KEY not configured" });
    }

    // ── POLL MODE ──
    if (pollTaskId) {
      const resp = await fetch(`${KIE_RECORD_INFO_ENDPOINT}?taskId=${pollTaskId}`, {
        headers: { Authorization: `Bearer ${KIE_API_KEY}` },
      });
      const rawText = await resp.text();
      console.log(`[grok-edit] poll action=${action} taskId=${pollTaskId} HTTP:${resp.status} body:${rawText.slice(0, 500)}`);

      if (!resp.ok) {
        return json({ success: false, status: "error", error: `KIE poll HTTP ${resp.status}` });
      }

      const j = JSON.parse(rawText);
      const rawStatus = (j?.data?.state || j?.data?.status || j?.data?.taskStatus || "").toString().toLowerCase();
      const isDone = rawStatus === "success" || rawStatus === "completed" || rawStatus === "finished"
        || rawStatus === "succeed" || rawStatus === "done" || rawStatus === "2";
      const isFailed = rawStatus === "failed" || rawStatus === "error" || rawStatus === "fail" || rawStatus === "3";

      if (isFailed) {
        return json({ success: false, status: "failed", error: `KIE task failed: ${j?.data?.failMsg || rawStatus}` });
      }
      if (!isDone) {
        return json({ success: true, status: "pending", rawStatus });
      }

      if (action === "segment") {
        let parsedResult: any = null;
        try { parsedResult = typeof j?.data?.resultJson === "string" ? JSON.parse(j.data.resultJson) : j?.data?.resultJson; } catch { /* ignore */ }
        const rawSegments = findSegments(parsedResult ?? j?.data);
        const segments = rawSegments
          .map(normalizeSegment)
          .filter((s): s is NonNullable<typeof s> => !!s)
          .slice(0, MAX_SEGMENTS);

        // Attach masks as base64 data URLs so the browser can hit-test pixels without CORS issues
        const withMasks = await Promise.all(segments.map(async (seg) => ({
          name: seg.name,
          index: seg.index,
          maskDataUrl: seg.maskUrl ? await fetchMaskAsDataUrl(seg.maskUrl) : "",
        })));

        await logAIFromRequest(req, {
          functionName: "wakti-grok-image-edit",
          provider: "kie-grok",
          model: MODEL_SEGMENT,
          status: "success",
          durationMs: Date.now() - startTime,
          metadata: { taskId: pollTaskId, segmentCount: withMasks.length },
        });
        return json({ success: true, status: "done", segments: withMasks });
      }

      // action === "edit" → extract image URLs
      const imageUrls = extractImageUrls(j?.data);
      if (imageUrls.length === 0) {
        return json({ success: false, status: "failed", error: `Done but no images: ${JSON.stringify(j?.data).slice(0, 200)}` });
      }

      // Edit counts as one image against the t2i quota (Kie charges the same 4 credits)
      const trialPayload = userId
        ? buildTrialSuccessPayload("t2i", await checkAndConsumeTrialTokenOnce(supabase, userId, "t2i", 2, pollTaskId))
        : null;

      await logAIFromRequest(req, {
        functionName: "wakti-grok-image-edit",
        provider: "kie-grok",
        model: MODEL_EDIT,
        status: "success",
        durationMs: Date.now() - startTime,
        metadata: { taskId: pollTaskId, imageCount: imageUrls.length },
      });
      return json({ success: true, status: "done", urls: imageUrls, trial: trialPayload });
    }

    // ── SUBMIT MODE ──
    const sourceTaskId: string = (body?.task_id || "").toString().trim();
    if (!sourceTaskId) {
      return json({ success: false, error: "Missing task_id" });
    }

    let model = MODEL_SEGMENT;
    let input: Record<string, unknown> = { task_id: sourceTaskId };

    if (action === "edit") {
      const prompt: string = (body?.prompt || "").toString().trim();
      if (!prompt) {
        return json({ success: false, error: "Missing prompt" });
      }

      const promptSafety = inspectGenerationPrompt(prompt, language);
      if (!promptSafety.allowed) {
        return json({ success: false, error: promptSafety.message });
      }

      if (userId) {
        const trial = await checkTrialAccess(supabase, userId, "t2i", 2);
        if (!trial.allowed) {
          return json({ success: false, ...buildTrialErrorPayload("t2i", trial) }, 403);
        }
      }

      model = MODEL_EDIT;
      input = { prompt: promptSafety.normalizedPrompt, task_id: sourceTaskId };
      const maskIndexes = Array.isArray(body?.mask_indexs)
        ? body.mask_indexs.map((n: any) => Number(n)).filter((n: number) => Number.isFinite(n))
        : [];
      if (maskIndexes.length > 0) {
        input.mask_indexs = maskIndexes;
      }
    }

    const submitToKie = async (endpoint: string) => {
      const resp = await fetch(endpoint, {
        method: "POST",
        headers: { Authorization: `Bearer ${KIE_API_KEY}`, "Content-Type": "application/json" },
        body: JSON.stringify({ model, input }),
      });
      return { resp, text: await resp.text() };
    };

    // Kie's documented /client/tasks endpoint 404s on the public API (playground-only for now),
    // so the proven unified door goes first; client/tasks stays as a future-proof fallback.
    let { resp: submitResp, text: submitText } = await submitToKie(KIE_CREATE_TASK_ENDPOINT);
    console.log(`[grok-edit] submit action=${action} source=${sourceTaskId} via jobs/createTask HTTP:${submitResp.status} body:${submitText.slice(0, 400)}`);

    if (submitResp.status === 404) {
      ({ resp: submitResp, text: submitText } = await submitToKie(KIE_CLIENT_TASKS_ENDPOINT));
      console.log(`[grok-edit] submit fallback via client/tasks HTTP:${submitResp.status} body:${submitText.slice(0, 400)}`);
    }

    if (!submitResp.ok) {
      throw new Error(`KIE submit failed ${submitResp.status}: ${submitText.slice(0, 200)}`);
    }
    const submitJson = JSON.parse(submitText);
    const newTaskId = submitJson?.data?.taskId;
    if (!newTaskId) {
      const kieMsg = (submitJson?.msg || "").toString();
      if (/original task id/i.test(kieMsg)) {
        throw new Error("EDIT_SESSION_EXPIRED");
      }
      throw new Error(`No taskId in KIE response: ${submitText.slice(0, 200)}`);
    }

    return json({ success: true, status: "submitted", taskId: newTaskId });
  } catch (err: any) {
    const msg = err?.message || String(err);
    console.error(`[grok-edit] error:`, msg);
    await logAIFromRequest(req, {
      functionName: "wakti-grok-image-edit",
      provider: "kie-grok",
      model: logModel,
      status: "error",
      errorMessage: msg,
      durationMs: Date.now() - startTime,
    });
    return json({ success: false, error: msg }, 500);
  }
});
