-- Smart File Generator: Track generated files
CREATE TABLE IF NOT EXISTS public.generated_files (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Input metadata
  input_type TEXT NOT NULL CHECK (input_type IN ('text', 'pdf', 'docx', 'txt', 'mixed')),
  input_file_name TEXT,
  input_file_size_bytes INT,
  
  -- Output metadata
  output_type TEXT NOT NULL CHECK (output_type IN ('pptx', 'docx', 'pdf')),
  output_size INT NOT NULL, -- slides or pages
  output_language TEXT NOT NULL CHECK (output_language IN ('en', 'ar')),
  
  -- Generated file
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL, -- storage path
  file_size_bytes INT,
  download_url TEXT,
  
  -- Status tracking
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  error_message TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ -- optional: for auto-cleanup
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_generated_files_user_id ON public.generated_files(user_id);
CREATE INDEX IF NOT EXISTS idx_generated_files_created_at ON public.generated_files(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_generated_files_status ON public.generated_files(status);
CREATE INDEX IF NOT EXISTS idx_generated_files_expires_at ON public.generated_files(expires_at) WHERE expires_at IS NOT NULL;

-- RLS Policies
ALTER TABLE public.generated_files ENABLE ROW LEVEL SECURITY;

-- Users can only see their own generated files
CREATE POLICY "Users can view own generated files"
  ON public.generated_files
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own generation requests
CREATE POLICY "Users can create generation requests"
  ON public.generated_files
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own files (for status tracking)
CREATE POLICY "Users can update own generated files"
  ON public.generated_files
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can delete their own files
CREATE POLICY "Users can delete own generated files"
  ON public.generated_files
  FOR DELETE
  USING (auth.uid() = user_id);

-- Optional: Auto-cleanup function for expired files
CREATE OR REPLACE FUNCTION cleanup_expired_generated_files()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.generated_files
  WHERE expires_at IS NOT NULL
    AND expires_at < NOW();
END;
$$;

-- Optional: Schedule cleanup job (if pg_cron is enabled)
-- SELECT cron.schedule(
--   'cleanup-expired-generated-files',
--   '0 * * * *', -- Every hour
--   'SELECT cleanup_expired_generated_files();'
-- );

COMMENT ON TABLE public.generated_files IS 'Tracks files generated by Smart File Generator feature';
